### ISSUE TITLE
Invalid Syntax Error

### ISSUE THREAD

**Issue by martinweingart** [Evolution0/bandcamp-dl#102]
Python version: 2.7  

Bandcamp-dl version: 0.0.7

Bancamp-dl options: any

I have this error when trying to run bandcamp-dl when any options (for example, "bandcamp-dl -h"):

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp_dl.py", line 49, in <module>
    from .bandcamp import Bandcamp
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp.py", line 10
    def parse(self, url: str, art: bool=True) -> dict or None:
                       ^
SyntaxError: invalid syntax

-------------------------

**Comment by Evolution0** [comment]
Python 2.7 is not supported (And I've recently made changes to prevent it from installing in the future), I would suggest updating to Python 3.

I could suggest using an older version like 0.0.5 but the bugs and features missing just wouldn't be worth it really.

If you are locked in a situation where moving to Python 3 is just not an option I suggest you take a look at [SoundScrape](https://github.com/Miserlou/SoundScrape), it should allow you to download just fine.

**Comment by martinweingart** [comment]
Ok thanks a lot!
