### ISSUE TITLE
Album download with "--embed-lyrics" fails on tracks with no lyrics

### ISSUE THREAD

**Issue by FireStarW** [Evolution0/bandcamp-dl#105]
**Python version:**  
Python 3.5.2+

**Bandcamp-dl version:**
bandcamp-dl 0.0.7-09
**Bandcamp-dl options:**  
bandcamp-dl https://theunlovables.bandcamp.com/album/crush-boyfriend-heartbreak --template=%{title} --embed-lyrics --base-dir=/media/VR32/Sounds\ and\ music/Rock/aaaa

**url:**  
https://theunlovables.bandcamp.com/album/crush-boyfriend-heartbreak

**Describe the issue:**
-------------------------
Using the --embed-lyrics option when downloading an album seems to fail on a track with no lyrics, in the linked albums case, it is the last track.

bandcamp-dl itself gives this output at the end(Using Ubuntu, so linux style file paths):

`(13/13) [==================================================] :: Encoding: inconsolableTraceback (most recent call last):
  File "/home/dustin/.local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/home/dustin/.local/lib/python3.5/site-packages/bandcamp_dl/__main__.py", line 92, in main
    bandcamp_downloader.start(album)
  File "/home/dustin/.local/lib/python3.5/site-packages/bandcamp_dl/bandcampdownloader.py", line 52, in start
    self.download_album(album)
  File "/home/dustin/.local/lib/python3.5/site-packages/bandcamp_dl/bandcampdownloader.py", line 167, in download_album
    self.write_id3_tags(filepath, track_meta)
  File "/home/dustin/.local/lib/python3.5/site-packages/bandcamp_dl/bandcampdownloader.py", line 201, in write_id3_tags
    audio["USLT"] = USLT(encoding=3, lang='eng', desc='', text=meta['lyrics'])
KeyError: 'lyrics'
`

It also seems that even though all the other songs have lyrics in the tags the lyrics field just contains "lyrics unavailable"

**Comment by Evolution0** [comment]
Yep, its useless atm, there was some bugfixes that needed to be pushed out some time ago and the code got included accidentally so rather than revert or make another commit I left it in.

Took me a while to figure out the best way to get the lyrics (which I eventually did) but the feature is still on the back burner due to other projects.

**Comment by AlessandroAnnini** [comment]
I was the one who pushed the lyrics feature at first and now i accidentally have seen this issue so I made a [pull request](https://github.com/iheanyi/bandcamp-dl/pull/107) with a simple bugfix following @FireStarW indications.

**Comment by Evolution0** [comment]
Lyrics embedding properly implemented now, closing.
