### ISSUE TITLE
'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by ibrokemypie** [Evolution0/bandcamp-dl#110]
**Python version:**  3.6

**Bandcamp-dl version:**  0.0.7-09

**Bancamp-dl options:**  bandcamp-dl --artist=iamsleepless --album=mirrors-of-a-still-sky

**url:**  https://iamsleepless.bandcamp.com/track/mirrors-of-a-still-sky

**options:**  

**Describe the issue:**
-------------------------

$ bandcamp-dl --artist=iamsleepless --album=mirrors-of-a-still-sky
bandcamp-dl

Usage:
    bandcamp-dl [url]
    bandcamp-dl [--template=<template>] [--base-dir=<dir>]
                [--full-album]
                (<url> | --artist=<artist> --album=<album>)
                [--overwrite]
                [--no-art]
                [--embed-lyrics]
                [--group]
    bandcamp-dl (-h | --help)
    bandcamp-dl (--version)

Options:
    -h --help                   Show this screen.
    -v --version                Show version.
    -a --artist=<artist>        The artist's slug (from the URL)
    -b --album=<album>          The album's slug (from the URL)
    -t --template=<template>    Output filename template.
                                [default: %{artist}/%{album}/%{track} - %{title}]
    -d --base-dir=<dir>         Base location of which all files are downloaded.
    -f --full-album             Download only if all tracks are available.
    -o --overwrite              Overwrite tracks that already exist. Default is False.
    -n --no-art                 Skip grabbing album art
    -e --embed-lyrics           Embed track lyrics (If available)
    -g --group                  Use album/track Label as iTunes grouping

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.7.post9', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/HEAD-609ad3a/libexec/lib/python3.6/site-packages/bandcamp_dl/__main__.py", line 100, in main
    album = bandcamp.parse(url)
  File "/usr/local/Cellar/bandcamp-dl/HEAD-609ad3a/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcamp.py", line 45, in parse
    bandcamp_json = BandcampJSON(self.soup).generate()
  File "/usr/local/Cellar/bandcamp-dl/HEAD-609ad3a/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 34, in generate
    self.js_to_json()
  File "/usr/local/Cellar/bandcamp-dl/HEAD-609ad3a/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 58, in js_to_json
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/HEAD-609ad3a/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 46, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by Evolution0** [comment]
Don't feed it an album name if you are only attempting to download a single track.

**Comment by ibrokemypie** [comment]
What is the syntax for one track then?

**Comment by Evolution0** [comment]
You don't actually need to use artist/album, just feed it the url directly. Those options are there if you want to download a specific album from a specific artist without using the url. Track downloading wasn't originally supported (But now is) and a --track option hasn't been added yet (Mostly because most tracks are part of an album, so tricky)

**Comment by RomanHargrave** [comment]
@Evolution0 I'm having this problem, except I _want_ to download an album. The `--artist=... --album=...` nor `artist.bandcamp.com/album/album_name` approach work, both arrive at this apparent issue with beautifulsoup.
