### ISSUE TITLE
Spaces in the names

### ISSUE THREAD

**Issue by davidoskky** [Evolution0/bandcamp-dl#112]
**Python version:**  
3.5.2
**Bandcamp-dl version:**
0.0.7-09

-------------------------

When the name of the artist or of the album contains a space in between two words this is replaced with a -

The result doesn't change even using the options --artist and --album: the music is correctly downloaded even typing the spaces but the resulting files do contain the -

This fact is quite annoying as you ought to manually modify the names of the folders.

**Comment by Evolution0** [comment]
At some point I suppose I can phase this behavior out but its not critical as when loaded into a suitable player you don't see the filenames; you see the ID3 tags anyway.

AFAIK this is done by Slugify which was used long before I started maintaining the project, perhaps I need to take a look at why its actually used.

**Comment by Evolution0** [comment]
`--no-slugify` option added, `pip install bandcamp-downloader --upgrade` to get the latest release.
