### ISSUE TITLE
Traceback error 

### ISSUE THREAD

**Issue by kandersk** [Evolution0/bandcamp-dl#117]
**Python version:**  3.6

**Bandcamp-dl version:** Current as of (May 11th 2017)

**Bancamp-dl options:**  Album download

**url:**  https://mfdoom.bandcamp.com/album/mm-food

**options:**  

**Describe the issue:**
-------------------------
When attempting `bandcamp-dl https://mfdoom.bandcamp.com/album/mm-food ` 
I get 
`Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/bandcamp_dl/__main__.py", line 100, in main
    arguments['--embed-art'], arguments['--no-slugify'])
KeyError: '--embed-art'`

**Comment by Evolution0** [comment]
Delete any old not.finished files, its attempting to resume a previously run command that uses an argument that is no longer available.

**Comment by kandersk** [comment]
Thank you so much! This fixed the issue!
