### ISSUE TITLE
ImportError: No module named 'bandcamp_dl'

### ISSUE THREAD

**Issue by Maccer1** [Evolution0/bandcamp-dl#122]
**Python version:**  
I have both python 3.5.2 and 2.7
**Bandcamp-dl version:**
lastest avaliable from pip
**Describe the issue:**
```
$ bandcamp-dl --base-dir=~/Downloads/ https://milkteethpunx.bandcamp.com/album/vile-child
Traceback (most recent call last):
  File "/home/nicolas/.local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
ImportError: No module named 'bandcamp_dl'
```

-------------------------

**Comment by Evolution0** [comment]
I don't support 2.7, as for 3.5.2 are you absolutely sure that it was being used?

I've gotten reports like this before and it ended up being that after updating Python the system was still defaulting to the old version.

Can you do a: `python --version` to see?

**Comment by Maccer1** [comment]
I've created an alias before, so when executing `python --version ` I get 3.5.2 as it should be.
But somehow it still uses python2.7 to execute bandcamp-dl..

I think the issue could be that I use pip instead of pip3 to install bandcamp-dl. However when I try pip3 i get this
```
$ pip3 install bandcamp-dl
Collecting bandcamp-dl
  Could not find a version that satisfies the requirement bandcamp-dl (from versions: )
No matching distribution found for bandcamp-dl

```

I'm also using pip 8.1.1 because I can't upgrade to 9.0.1 with ` pip install --upgrade pip`. If I do that it breaks pip.

**Comment by Maccer1** [comment]
Well, I've installed it from source with  `python3 setup.py install --user ` and unistalled the one from pip. This way it works, but the issue persists since it should work installing it from pip as well.

**Comment by Evolution0** [comment]
Yeah an alias won't help if Python 2.7 is the first it runs into in your PATH, it would be different if this was a standalone script where its launched traditionally (e.g `python bandcamp-dl.py etc etc`)

In the case of bandcamp-dl and the current distribution process it actually creates a small executable called bandcamp-dl that calls the actual code (for windows its Python's `Scripts` dir, for unix/linux `.local/bin` AFAIK)

Its a strange error you have run into, I actually have had (and still do) multiple versions of Python installed on top of 2.7 and pip works without issue.

Makes me curious if this is a unix/linux specific issue.

Its not something I can test immediately as Id need to set up a virtual machine but I will keep this issue up till I get around to it. Thanks for reporting it.

**Comment by Evolution0** [comment]
Have not been able to reproduce this, assuming this was some strange system specific quirk.
