### ISSUE TITLE
Improvement: Support genre tag in the filepath template

### ISSUE THREAD

**Issue by Nzen** [Evolution0/bandcamp-dl#125]
I, and [reputedly others](https://www.bogleheads.org/forum/viewtopic.php?t=168622) prefer to include genre in our music folder structure. It would be cool if bandcamp-dl supported including the album's genre as part of the filepath template.

I see that bandcamp albums don't have a canonical genre tag, just tags an artist applied to the album. (For discoverability, though, each is likely to include a core genre.) Including all the tags may brush up [against the limits](https://mclowe.bandcamp.com/album/first-of-all-mixtape) of path length. Such a feature would probably only propagate the core genres on bandcamp's landing page. I emphasize core, because artists typically put 'duplicates' with different spellings or hyphenation for SEO.

I propose that a filepath template with _%{genres}_ replace that tag with a comma separated, no-spaces string of the core genre tags. (Slugification removes the commas.) Where an album does not use one of the core genres, bandcamp-dl could substitute _none_ .
* ex: Piraton Record's song [Space Dynamite](https://piratonrecords.bandcamp.com/track/space-dynamite-sand-a) produces _latin,punk,pop_ . It does not include "hip hop" because the canon filter is "hip-hop/rap".

**Comment by Evolution0** [comment]
The first problem here is what exactly the core genres _are_; Bandcamp actually has a list of [legitimate tags](https://bandcamp.com/tags) which without even considering alternate spellings by the artist leave the possibility of exceeding the path length.

Now I _could_ simply retrieve all the tags listed on the track/album page and remove any that do not match Bandcamp's official tags then retain the first **_n_** tags remaining and call it good.

The second problem that has me worried is that artists may not necessarily prioritize putting their most relevant tags first making it unreliable and in some cases defeating the purpose of retrieving them (Easing identification, organization, and filtering)

**Comment by v-fox** [comment]
Hey, guys, can you add the "year" tag while you're at it ? How do you even have discographies without them being sorted by year under the artist directory [rhetorical] ?
