### ISSUE TITLE
Generates not.finished file for complete downloads while run from an external application

### ISSUE THREAD

**Issue by ghost** [Evolution0/bandcamp-dl#133]
**Python version:**  3.5.4 

**Bandcamp-dl version:** 0.0.8.post6

**Bancamp-dl options:**  --debug --base-dir=/home/sernick/Temp 

**url:**  https://overwerk.bandcamp.com/album/conquer

**options:**  

**Describe the issue:**
-------------------------
I've made a little app in C++, and I'm calling the bandcamp-dl via system() command and it crashes. Same command from terminal runs fine.
	
URL:https://overwerk.bandcamp.com/album/conquerhttps://overwerk.bandcamp.com/album/conquer
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): overwerk.bandcamp.com   
DEBUG:urllib3.connectionpool:https://overwerk.bandcamp.com:443 "GET/album/conquerhttps://overwerk.bandcamp.com/album/conquer HTTP/1.1" 404 None   
DEBUG:root: Generating BandcampJSON..  
DEBUG:root: Grabbing target data..   
DEBUG:root: Converting JS to JSON..   
DEBUG:root: Grabbing embedded script..   
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/__main__.py", line 91, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by Evolution0** [comment]
Looking at your debug log it seems like you are mashing two copies of the URL together though which wouldn't get you far 😋

If this is somehow behavior caused by bandcamp-dl itself though I'm totally willing to look into it. The only thing I could possibly think of that could cause that though is if a user used the `--artist` `--album` options while also providing a URL (They are mutually exclusive), can't remember if that is possible or not though as its been a while.

**Comment by ghost** [comment]
Yeah, the problem looks like a doubled URL. The problem is that I launch bandcamp-dl with correct syntax, that works in a terminal, but not via the system() command. It just looks like it doubles the URL by itself.
Another example:
```
bandcamp-dl --debug --base-dir='/home/sernick/Temp' https://scandroid.bandcamp.com/album/the-force-theme-single
DEBUG:root:
        URL: https://scandroid.bandcamp.com/album/the-force-theme-singlehttps://scandroid.bandcamp.com/album/the-force-theme-single
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): scandroid.bandcamp.com
DEBUG:urllib3.connectionpool:https://scandroid.bandcamp.com:443 "GET /album/the-force-theme-singlehttps://scandroid.bandcamp.com/album/the-force-theme-single HTTP/1.1" 404 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/__main__.py", line 91, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcamp.py", line 40, in parse
 bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by ghost** [comment]
Ok, so apparently debug printing from the app was the reason for doubled URLs (I know it sounds stupid, but hey). After turning debug off I can download only one album, because the first download creates a 0.0.8-06.not.finished file (even though the download is successful) and all other next system() calls instead of downloading another url, just try to redownload the first one.
```
DEBUG:root:
	URL: https://scandroid.bandcamp.com/album/the-force-theme-single
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): scandroid.bandcamp.com
DEBUG:urllib3.connectionpool:https://scandroid.bandcamp.com:443 "GET /album/the-force-theme-single HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: BandcampJSON generated..
DEBUG:root: Generating Album..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Album generated..
DEBUG:root: Album data:
	{'date': '2017', 'tracks': [{'duration': 323.084, 'track': '1', 'url': 'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=6c52c44b7acfc7108679e2180bf35736&id=2601497724&stream=1&ts=1505026865.0', 'title': 'The Force Theme'}], 'label': 'FiXT', 'full': True, 'art': 'https://f4.bcbits.com/img/a1852508397_16.jpg', 'artist': 'Scandroid', 'title': 'The Force Theme (Single)'}
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
DEBUG:root: Generating filepath/trackname..
DEBUG:root: filepath/trackname generated..
DEBUG:root:
	Path: /home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3
DEBUG:root: Directory:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single
DEBUG:root: Directory doesn't exist, creating..
DEBUG:root: Current file:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3.tmp
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f4.bcbits.com
DEBUG:urllib3.connectionpool:https://f4.bcbits.com:443 "GET /img/a1852508397_16.jpg HTTP/1.1" 200 56240
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): popplers5.bandcamp.com
DEBUG:urllib3.connectionpool:http://popplers5.bandcamp.com:80 "GET /download/track?enc=mp3-128&fsig=6c52c44b7acfc7108679e2180bf35736&id=2601497724&stream=1&ts=1505026865.0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): p4.bcbits.com
DEBUG:urllib3.connectionpool:http://p4.bcbits.com:80 "GET /download/track/4fec66f8f27a6b1647d411ca64115620/mp3-128/2601497724?fsig=7a50b7b192b2d7c2213754bb4f4c3231&id=2601497724&stream=1&ts=1505073600.0&token=1505073660_a5d31c3b01fc80a3cdd7eddb0cf13de9ff03418e HTTP/1.1" 200 5261718
DEBUG:root: Encoding process starting..
DEBUG:root: Encoding process finished..
DEBUG:root: Renaming:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3.tmp -to-> /home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3
### bandcamp-dl ran again with new URL here
DEBUG:root:
	URL: https://scandroid.bandcamp.com/album/the-force-theme-single
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): scandroid.bandcamp.com
DEBUG:urllib3.connectionpool:https://scandroid.bandcamp.com:443 "GET /album/the-force-theme-single HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: BandcampJSON generated..
DEBUG:root: Generating Album..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Album generated..
DEBUG:root: Album data:
	{'tracks': [{'duration': 323.084, 'track': '1', 'title': 'The Force Theme', 'url': 'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=6c52c44b7acfc7108679e2180bf35736&id=2601497724&stream=1&ts=1505026865.0'}], 'artist': 'Scandroid', 'label': 'FiXT', 'title': 'The Force Theme (Single)', 'full': True, 'date': '2017', 'art': 'https://f4.bcbits.com/img/a1852508397_16.jpg'}
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
DEBUG:root: Generating filepath/trackname..
DEBUG:root: filepath/trackname generated..
DEBUG:root:
	Path: /home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3
DEBUG:root: Directory:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single
DEBUG:root: Directory doesn't exist, creating..
DEBUG:root: Current file:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3.tmp
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): popplers5.bandcamp.com
DEBUG:urllib3.connectionpool:http://popplers5.bandcamp.com:80 "GET /download/track?enc=mp3-128&fsig=6c52c44b7acfc7108679e2180bf35736&id=2601497724&stream=1&ts=1505026865.0 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): p4.bcbits.com
DEBUG:urllib3.connectionpool:http://p4.bcbits.com:80 "GET /download/track/4fec66f8f27a6b1647d411ca64115620/mp3-128/2601497724?fsig=7a50b7b192b2d7c2213754bb4f4c3231&id=2601497724&stream=1&ts=1505073600.0&token=1505073660_a5d31c3b01fc80a3cdd7eddb0cf13de9ff03418e HTTP/1.1" 200 5261718
File: 01 - the-force-theme.mp3 already exists and is complete, skipping..
```
First URL:https://scandroid.bandcamp.com/album/the-force-theme-single
Second URL: https://scandroid.bandcamp.com/album/a-thousand-years-single
When I try to delete the 0.0.8-06.not.finished file I get the same error as in my second comment.

**Comment by Evolution0** [comment]
Doesn't sound stupid at all, sounds like I might have an issue with my debug option.

As for the not.finished file not being deleted that has actually been fixed since 0.0.8-06 by @Nzen I simply had not pushed a new release since.. my bad, I'll do that now.

Edit: Some changes were done on PyPI (New site is being pushed, changes in upload procedure) but I got the new release out 😸 Let me know if it works now.

**Comment by ghost** [comment]
Thanks for the update! Unfortunately, now things got even weirder. The 0.0.8-07 file is generated after the first download, and during the second download it disappears for a moment only to appear again, but this time with the second url appended to the urlstring.
```
{'--album': None, '--artist': None, '--base-dir': '/home/sernick/Temp/Downloads', '--debug': True, '--embed-art': False, '--embed-lyrics': False, '--full-album': False, '--group': False, '--help': False, '--no-art': False, '--no-slugify': False, '--overwrite': False, '--template': '%{artist}/%{album}/%{track} - %{title}', '--track': None, '--version': False, 'URL': 'https://scandroid.bandcamp.com/album/the-force-theme-singlehttps://scandroid.bandcamp.com/album/a-thousand-years-single'}
```

**Comment by Evolution0** [comment]
Strange I just updated and grabbed both of those just fine (even running the commands back to back very quickly in the same directory)

Id be interested in seeing exactly how you are calling bandcamp-dl in your code and how urls are stored/passed.

**Comment by Evolution0** [comment]
If your codes purpose is for downloading in batches keep in mind that Bandcamp limits connections, so downloading more at once only slows down each individual download (Unless you support proxies)

Otherwise if you are just writing an app to make downloading multiple tracks/albums more convenient I could always make passing multiple urls work, docopt supports such things natively so I doubt it would take much work.

**Comment by ghost** [comment]
I'm actually making a simple gui as a programming exercise . All it does is collect urls from user, and then (in a loop) cycles through them all, and in each cycle it calls bandcamp-dl with a few options and one url ([Link](http://www.mediafire.com/file/94nxx6qo7nsdqb8/gui.zip)) . But multiple url support would be pretty helpful in this case.

**Comment by Evolution0** [comment]
For now here is a version that will ignore the not.finished file if a url is provided: 
[bandcamp_downloader-0.0.8.post8.dev0-py3-none-any.zip](https://github.com/iheanyi/bandcamp-dl/files/1327547/bandcamp_downloader-0.0.8.post8.dev0-py3-none-any.zip)

Just extract that and `pip install` the resulting .whl file.

Keep in mind https://scandroid.bandcamp.com/album/a-thousand-years-single no longer exists so that is a guaranteed failure if you try to download it.

Now if it still breaks at least I know its not related to the session file. If it does work then I can rest easy and start working on cleaning this change up and implementing batch downloads (multi-url support)

**Comment by Evolution0** [comment]
@8sync Any update on this?

Make sure to update to the latest release as well since Bandcamp has had some internal changes:
`pip install --upgrade bandcamp-downloader`

To use the latest dev build:
`pip install bandcamp-downloader==0.0.9.dev0`

**Comment by ghost** [comment]
Sorry for a delayed response. So the new stable and dev builds behave same as before, and the modified build (thanks for the special version btw) fails altogether (even when downloading only one album).
Log from the modified version:
```
DEBUG:root:
	URL: https://scandroid.bandcamp.com/album/the-force-theme-single
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): scandroid.bandcamp.com
DEBUG:urllib3.connectionpool:https://scandroid.bandcamp.com:443 "GET /album/the-force-theme-single HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: BandcampJSON generated..
DEBUG:root: Generating Album..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Album generated..
DEBUG:root: Album data:
	{'date': '2017', 'artist': 'Scandroid', 'title': 'The Force Theme (Single)', 'art': 'https://f4.bcbits.com/img/a1852508397_16.jpg', 'tracks': [{'url': 'http:https://t4.bcbits.com/stream/232027152f787d1c6abfe69de755cdc7/mp3-128/2601497724?p=0&ts=1506694880&t=69782ba1ec31d0ee3bee6933b2dfcac73faefa66&token=1506694880_cccef40571176c31a65e03e7520e62a924c7bfcf', 'title': 'The Force Theme', 'duration': 323.084, 'track': '1'}], 'label': 'FiXT', 'full': True}
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
DEBUG:root: Generating filepath/trackname..
DEBUG:root: filepath/trackname generated..
DEBUG:root:
	Path: /home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3
DEBUG:root: Directory:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single
DEBUG:root: Directory doesn't exist, creating..
DEBUG:root: Current file:
	/home/sernick/Temp/Downloads/scandroid/the-force-theme-single/01 - the-force-theme.mp3.tmp
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): f4.bcbits.com
DEBUG:urllib3.connectionpool:https://f4.bcbits.com:443 "GET /img/a1852508397_16.jpg HTTP/1.1" 200 56240
No connection adapters were found for 'http:https://t4.bcbits.com/stream/232027152f787d1c6abfe69de755cdc7/mp3-128/2601497724?p=0&ts=1506694880&t=69782ba1ec31d0ee3bee6933b2dfcac73faefa66&token=1506694880_cccef40571176c31a65e03e7520e62a924c7bfcf'
Downloading failed..
```

**Comment by Evolution0** [comment]
Yeah an issue was reported after I built that version which pointed me towards a change Bandcamp made which results in that error (They now include the protocol in the url, it used to just be //t4bcbits/com/etc etc) Its fixed in the latest.

I can't figure out why calling bandcamp-dl in a loop with individual urls would break, there is no logical reason for it especially considering this is not the first time it has been used externally like this.

I looked at the code and didn't notice anything that would be an issue either. Have you tried adding a print for the url variable and see if its actually doubling up before it gets to bandcamp-dl?

**Comment by ghost** [comment]
> Have you tried adding a print for the url variable and see if its actually doubling up before it gets to bandcamp-dl?

Yeah, initially when starting this issue I had something like that in my code, and the urls were extracted from the text field just fine. And every time the loop starts a new cycle, you can see the command which is being executed and imo they look perfectly fine, and when entered manually into a terminal, they also work perfectly fine.

> I can't figure out why calling bandcamp-dl in a loop with individual urls would break, there is no logical reason for it especially considering this is not the first time it has been used externally like this.

Exactly.
