### ISSUE TITLE
One out of multiple tracks from an album doesnt have any metadata 

### ISSUE THREAD

**Issue by ghost** [Evolution0/bandcamp-dl#136]
**Python version:**  
3.6.3-1
**Bandcamp-dl version:**
0.0.9-dev
**Bandcamp-dl options:**  
none
**url:**  
https://celer.bandcamp.com/album/panoramic-dreams-bathed-in-seldomness
**options:**  
none
**Describe the issue:**
-------------------------
`ffprobe Who\ Feels\ Like\ Me,\ Who\ Wants\ Like\ Me,\ Who\ Doubts\ Any\ Good\ Will\ Come\ Of\ This-2763854498.mp3 2>&1 | grep -A90 'Metadata:' `

    Metadata:
      encoder         : LAME3.98r
    Side data:
      replaygain: track gain - -0.800000, track peak - unknown, album gain - unknown, album peak - unknown, 

debug: http://ix.io/C70  -- wrong paste lol sorry

edit: ive redownloaded it and now its tagged. Weird. Dunno what caused it tho

**Comment by Evolution0** [comment]
Interesting.. first time I've heard of something like this happening, only way I can think of this happening is if:

-  `write_id3_tags()` didn't fire, but in that case the filename would still end in `.tmp`.
- `skip = True` Which should only happen if the file already existed.

I may add in an option to "integrity check" files after the download and encoding process is complete just to verify that everything is kosher, but as this seems to be something I can't reproduce immediately it will be on the back burner. Nevertheless thanks for reporting it.
