### ISSUE TITLE
Object has no attribute album_art

### ISSUE THREAD

**Issue by gpchelkin** [Evolution0/bandcamp-dl#137]
**Python version:**  3.5.2

**Bandcamp-dl version:** 0.0.9.dev0

**Bancamp-dl options:**  `--base-dir ~ --template "%{track} - %{artist} - %{title} [%{album}]" --overwrite --group --embed-art --no-slugify $url`

**url:**  https://blanckmass.bandcamp.com/album/white-math-polymorph

**options:**  

**Describe the issue:**
-------------------------
With `--embed-art`:
```
Track list incomplete, some tracks may be private, download anyway? (yes/no): yes
Starting download process.
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/__main__.py", line 106, in main
    bandcamp_downloader.start(album)
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampdownloader.py", line 57, in start
    self.download_album(album)
  File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcampdownloader.py", line 209, in download_album
    os.remove(self.album_art)
AttributeError: 'BandcampDownloader' object has no attribute 'album_art'
```
Without `--embed-art`:
```
Track list incomplete, some tracks may be private, download anyway? (yes/no): yes
Starting download process.
```
And nothing gets downloaded.

**Comment by Evolution0** [comment]
They are _all_ private tracks, makes sense nothing gets downloaded though the error could be more helpful.

**Comment by Evolution0** [comment]
I will at some point in the near future squash the error and have it return something useful in such a situation.
