### ISSUE TITLE
After downloading shorter track name part of previous one is seen

### ISSUE THREAD

**Issue by nrlquaker** [Evolution0/bandcamp-dl#138]
**Python version:**  
Python 3.6.4

**Bandcamp-dl version:**
bandcamp-dl 0.0.8-08

**Bancamp-dl options:**  
none

**url:**  
https://nebelung.bandcamp.com/album/palingenesis

**options:**  
none

**Describe the issue:**
-------------------------

After downloading track with shorter file name part of the previous one is seen in the end.
Here is the example in [asciinema](https://asciinema.org/a/ggdblpK0H11UbzV7PAcviL2Jr).

**Comment by Evolution0** [comment]
Yep, this is due to me using sys.stdout.flush()

**Comment by nrlquaker** [comment]
@Evolution0 It still [appears](https://asciinema.org/a/63auLxtx3IeVxullAogRyqSge) in 0.0.8-09.

**Comment by Evolution0** [comment]
This is starting to sound terminal specific, this does not happen in my IDE's terminal after the changes but does in CMD and I'm guessing whichever you use. Suppose I could do this the ugly way and just spam a whole line of blank characters before drawing another.

**Comment by Evolution0** [comment]
Did something a bit less ugly than I thought, upgrade and try again.

Should be a pretty foolproof solution, it takes the message to be printed, measures its length, subtracts that from the total width (in characters) of the terminal, then tacks on enough whitespace characters to fill the remainder.

**Comment by nrlquaker** [comment]
In 0.0.8-10 its not reproduces. Thanks!
