### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by arnauldb** [Evolution0/bandcamp-dl#140]
**Python version:**  
Python 2.7.12

**Bandcamp-dl version:**
latest
**Bancamp-dl options:**  
no

**url:**  
https://gonggonggong.bandcamp.com/album/rhythm-n-drone-ii

**options:**  
no

**Describe the issue:**
I have an error message after running 

> bandcamp-dl https://gonggonggong.bandcamp.com/album/rhythm-n-drone-ii

>   ~  $  bandcamp-dl https://gonggonggong.bandcamp.com/album/rhythm-n-drone-ii
> Traceback (most recent call last):
>   File "/usr/local/bin/bandcamp-dl", line 11, in <module>
>     load_entry_point('bandcamp-downloader==0.0.8.post10', 'console_scripts', 'bandcamp-dl')()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
>     return ep.load()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
>     return self.resolve()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "build/bdist.linux-x86_64/egg/bandcamp_dl/__main__.py", line 54, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/bandcamp_downloader-0.0.8.post10-py2.7.egg/bandcamp_dl/bandcamp.py", line 17
>     def parse(self, url: str, art: bool=True, lyrics: bool=False, debugging: bool=False) -> dict or None:
>                        ^

-------------------------

Thank you.

**Comment by Evolution0** [comment]
[Bandcamp-dl is Python 3.4 and up](https://github.com/iheanyi/bandcamp-dl#description).
