### ISSUE TITLE
Wrong v0.0.8-10 tag

### ISSUE THREAD

**Issue by nrlquaker** [Evolution0/bandcamp-dl#141]
v0.0.8-10 tag points to the v0.0.8-09 tag (1d82ca6). And fix for #138 is not included in v0.0.8-10.

**Comment by Evolution0** [comment]
Dammit, I was worried that would happen with the last release, I pushed the changes while I still had the draft open..

Deleting the release and republishing it should work fine, lets see..

**Comment by Evolution0** [comment]
Removed the broken release, it should be fine now.

**Comment by nrlquaker** [comment]
@Evolution0 Thanks.
