### ISSUE TITLE
Add audio format feature

### ISSUE THREAD

**Issue by billyschmidt** [Evolution0/bandcamp-dl#143]
Hi your tool is great but a format flag would be useful (--f ogg/flac/mp3)

**Python version:**  

**Bandcamp-dl version:**

**Bancamp-dl options:**  

**url:**  

**options:**  

**Describe the issue:**
-------------------------

**Comment by Evolution0** [comment]
The problem with that is dependencies; ffmpeg (or libav) specifically. You can't install ffmpeg from pip, on windows you need to download it separately and add it to your path and on *nix and mac you have to use a package manager.

This would take away the convenience of simply pip installing bandcamp-dl and using it immediately.

However all tracks are already MP3 so re-encoding would only be useful for dropping the quality to reduce filesize, as for FLAC as mentioned before all files are MP3, not much benefit in encoding a lossy file into a lossless format. I can see ogg and wav possibly being useful if you are trying to get the files to be playable with a web player _but its 2018_, [most if not all browsers now support MP3 natively](https://caniuse.com/#feat=mp3).

Its entirely possible to add the feature, I just don't see much point.

I'll leave the request open, if others are interested in it they can chime in and it may get added at some point, bandcamp-dl other than some minor tweaks and a bit of final cleanup is pretty much at its final stage, Id like to keep it as stable as possible for those using it in their own projects.

**Comment by rpgwaiter** [comment]
If you "purchase" an album (some are available for $0), you can download FLACs directly from bandcamp. Would it be possible to add FLAC downloading from free albums?
