### ISSUE TITLE
[Requst] Allow multiple urls download

### ISSUE THREAD

**Issue by RaitaroH** [Evolution0/bandcamp-dl#144]
**Python version:**  
```
python3 --version
Python 3.5.2
```
**Bandcamp-dl version:**
`bandcamp-dl 0.0.8-12`

**Describe the issue:**
-------------------------
I would like to be able to do something like:
`bandcamp-dl url1 url2 url3`
Actual result:
```
bdl https://sebastiangampl.bandcamp.com/album/city-hunter https://sebastiangampl.bandcamp.com/track/titanium-soldiers
Usage:
    bandcamp-dl [options] [URL]
```

**Comment by RaitaroH** [comment]
I guess, also having an option to download ALL the albums somebody made would be really cool too.

**Comment by Evolution0** [comment]
Discography downloading is something I have planned to do for some time now but just haven't gotten around to. Likely I would do the multiple URL handling first then adjust the parser to handle artist discography pages and simply pass that over as multiple urls.

Soon-ish, just other projects on my plate currently.

**Comment by superjamie** [comment]
In regards to the first request for multiple URL support, you can work around this with a shell function. This works with bash:

    bdl() { for URL in "$@"; do bandcamp-dl "$URL"; done; }

**Comment by superjamie** [comment]
Thank you!

For anyone looking, this is added with commit: https://github.com/iheanyi/bandcamp-dl/pull/160/commits/c7eb7eb66338ff93997c8cd7a1b6f0e0dd6a121e
