### ISSUE TITLE
[Request] Allow for spiting out urls to use for streaming

### ISSUE THREAD

**Issue by RaitaroH** [Evolution0/bandcamp-dl#145]
In essence I would like to get bandcamp-dl to spit out the mp3 links for a given url (cough cough artist) and then simply stream with something else. [Here[(https://www.youtube.com/watch?v=QczYT67JqYs) is an example video about something similar but not quite. So in that regard I could have a script that does idk something like
` bandcamp-dl --urls | bla bla bla` pretty much like in [this script](https://raw.githubusercontent.com/gotbletu/shownotes/master/w3m_scripts_collection/w3m_extbrowser_tmux_w3mplay_via_nvlc.sh). Or you know something like that.

**Comment by RaitaroH** [comment]
As an example you can do this with youtube-dl:
`youtube-dl --get-url --yes-playlist LINK` and it does exactly that.

```
youtube-dl --help | grep url
    --external-downloader COMMAND    Use the specified external downloader. Currently supports aria2c,avconv,axel,curl,ffmpeg,httpie,wget
    -g, --get-url                    Simulate, quiet but print URL
```

**Comment by Evolution0** [comment]
Since youtube-dl does it I'll likely add the functionality at some point.

**Comment by Evolution0** [comment]
Will be added when I do #150

**Comment by Evolution0** [comment]
Output will be a one-line comma delimited list unless someone has a better idea.
