### ISSUE TITLE
Question: What bitrate of MP3 Files are Downloaded?

### ISSUE THREAD

**Issue by Stunner** [Evolution0/bandcamp-dl#146]
I just stumbled upon this very interesting library and took a look at the source and it appears that mp3-128kbps bit rate is the default selected archive to download... is that correct? I personally try to download 320kpbs bitrate music wherever possible and would like to set that as the default bitrate to download in. Is this possible via some sort of flag or configuration setting? If not, what would you advise I change in the code?

Thanks in advance!

**Comment by ghost** [comment]
Yes, it seems like bandcamp-dl downloads mp3 files at 128kbps as that seems to be hardcoded into the program. I tried changing all references to mp3-128 in the bandcamp.py file to mp3-320 but after I installed the modified version and tried to download a track I got this error: 
```sh
Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

So yeah, I guess it's impossible to download mp3 files at 320kbps with bandcamp-dl unless I'm missing something.

**Comment by Stunner** [comment]
I made the same attempt and it gives that error because the change is made on a dictionary that only contains a mp3-128 entry.

I am now looking at how to create more or different entries for file that will allow for higher bit rates. If you or anyone else has some insight on how this information is parsed or created which could help that would be much appreciated. Thanks.

**Comment by Evolution0** [comment]
This isn't a matter of it being hardcoded into bandcamp-dl, its a matter of the source on Bandcamp which is used to fetch the tracks from only _being_ in 128kbps.

Tracks are retrieved from the same source the media player on the page uses, there is unfortunately no alternative. (Other than buying the tracks, which I am fine with and support)

**Comment by ghost** [comment]
Ah, that explains everything.

**Comment by Stunner** [comment]
@Evolution0 Thanks for clarifying and explaining where these tracks are being obtained from. Saved me a good few more hours continuing to reverse engineer this to ultimately find it isn't possible. May be worthwhile to mention this limitation and the reason for it in the README perhaps? If I make such a pull request will it be accepted?

**Comment by Evolution0** [comment]
@Stunner Go for it, the question just rarely came up so I never got around to explaining it in detail. Might be best to put a FAQ above the synopsis then later I can add answers to other questions users might have.

**Comment by kanliot** [comment]
I think this needs documentation that it only does the mp3.   Also the -y and --artist switches are confusing since I only have a vague idea what -y does, or why you would need not to pass it.
