### ISSUE TITLE
"SyntaxError: invalid syntax" from bandcamp-dl when running any command in Ubuntu 16.04

### ISSUE THREAD

**Issue by technotherion** [Evolution0/bandcamp-dl#148]
**Python version:**  Python 2.7.12

**Bandcamp-dl version:** -v won't run without errors to tell me which version; however it was installed about 20 mins ago by running `pip install bandcamp-download` using pip 9.0.3

**Bandcamp-dl options:**  n/a

**url:**  n/a

using Ubuntu 16.04 on Windows Linux Subsystem 

**Describe the issue:**
-------------------------
When running any command (e.g. `bandcamp-dl -h` or `bandcamp-dl -h --debug`, this "syntax error" occurs:

```Traceback (most recent call last):
  File "/home/mold/.local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.__main__ import main
  File "/home/mold/.local/lib/python2.7/site-packages/bandcamp_dl/__main__.py", line 54, in <module>
    from bandcamp_dl.bandcamp import Bandcamp
  File "/home/mold/.local/lib/python2.7/site-packages/bandcamp_dl/bandcamp.py", line 17
    def parse(self, url: str, art: bool=True, lyrics: bool=False, debugging: bool=False) -> dict or None:
                       ^
SyntaxError: invalid syntax```

**Comment by technotherion** [comment]
Issue was wrong python version.

**Comment by arnauldb** [comment]
@technotherion 

I have the same issue though I have both python 2 & 3 installed. How did you solve it?
Thank you.
