### ISSUE TITLE
Errno 13

### ISSUE THREAD

**Issue by publicenema** [Evolution0/bandcamp-dl#156]
**Python version:**  3.7.2.1

**Bandcamp-dl version:** bandcamp-dl-0.0.8-12_1.high_sierra.bottle.tar.gz

**Bancamp-dl options:**  - f, none, --debug

**url:**   https://doomtrip.bandcamp.com/album/blank-panthers-priest-expert-or-wizard-2

**options:**  

**Describe the issue:**
-------------------------
Sorry, I have no idea about programming, filing a proper issue and the meaning of the output from bandcamp-dl. Just wanted to use the handy tool.

otorongo:/ bummer$ bandcamp-dl -f https://doomtrip.bandcamp.com/album/blank-panthers-priest-expert-or-wizard-2
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_1/libexec/lib/python3.7/site-packages/bandcamp_dl/__main__.py", line 74, in main
    with open(session_file, "w") as f:
PermissionError: [Errno 13] Permission denied: '//0.0.8-12.not.finished'

otorongo:/ bummer$ bandcamp-dl https://doomtrip.bandcamp.com/album/blank-panthers-priest-expert-or-wizard-2
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_1/libexec/lib/python3.7/site-packages/bandcamp_dl/__main__.py", line 74, in main
    with open(session_file, "w") as f:
PermissionError: [Errno 13] Permission denied: '//0.0.8-12.not.finished'

otorongo:/ bummer$ bandcamp-dl --debug https://doomtrip.bandcamp.com/album/blank-panthers-priest-expert-or-wizard-2
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_1/libexec/lib/python3.7/site-packages/bandcamp_dl/__main__.py", line 74, in main
    with open(session_file, "w") as f:
PermissionError: [Errno 13] Permission denied: '//0.0.8-12.not.finished'

**Comment by Evolution0** [comment]
For some reason it seems your `basedir` is being set to just `/` so the filepath is coming out as `//0.0.8-12.not.finished` which is obviously invalid, might have something to do with this being a Brew install which I am wholly unfamiliar with. As far as I am aware they have worked properly previously..

Your current working directory should never be `/`, does this happen if for example you run this command from a folder on your desktop or somewhere else? If it works there I may need to put something in to prevent `basedir` from being root.

**Comment by Evolution0** [comment]
Closed until I get someone else that runs into it that I can get info from.
