### ISSUE TITLE
Typing definitions

### ISSUE THREAD

**Issue by Mattwmaster58** [Evolution0/bandcamp-dl#157]
What are your thoughts on upgrading the typing definitions? For example the old style `dict or None` could be changed to `Optional[dict]`. Of course, this will add one more requirement and an import statement in every file with update definintions.

**Comment by Evolution0** [comment]
I only use `dict or None` in two functions so changing those and adding additional requirements seems a little heavy handed for something with no real benefit.

Though it did make me notice that I have `dict or None` but then expect only `dict` in one function.

Last time I messed about with type definitions I cast aside Python 2 compatibility which cost me no end of trouble.
