### ISSUE TITLE
Track fails to download if it has the forward slash (/) in the title.

### ISSUE THREAD

**Issue by sumsare** [Evolution0/bandcamp-dl#165]
**Python version:**  
3.8.5

**Bandcamp-dl version:**
0.0.8-12

**Bancamp-dl options:**  
--no-slugify  --base-dir=[My Music Directory]

**url:**  
https://mikazukibigwave.bandcamp.com/track/memories

**Describe the issue:**
-------------------------
What the title says, as long as there is a forward slash in the title, I get an error such as [this](https://user-images.githubusercontent.com/69218230/93909244-7ba8c080-fcf7-11ea-9b0e-05b97727b74b.png).

**Comment by Evolution0** [comment]
I really need to overhaul filenaming and path validation.

Note to self: pathvalidate

**Comment by Evolution0** [comment]
Still need to look at pathvalidate but as I though fixing the weird unicode slugify module name overlap so that we are actually using it fixed a few filename errors, this now works.
