### ISSUE TITLE
Error in bandcampjson.py

### ISSUE THREAD

**Issue by bernard-crnkovic** [Evolution0/bandcamp-dl#168]
**Python version:**  3.7

**Bandcamp-dl version:**  0.0.8-12

**Bancamp-dl options:**  [URL]

**url:**  https://vvilderness.bandcamp.com/album/dark-waters

**options:** none

**Describe the issue:**

```
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/lib/python3.7/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/lib/python3.7/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/lib/python3.7/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/lib/python3.7/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```

-------------------------

**Comment by bernard-crnkovic** [comment]
Nevermind! cloned project, installed requirements, built with setup.py build, and now everything works fine.

**Comment by kanliot** [comment]
Ok, your results helped me, and is now working.  any idea why it stopped working? 

BTW, only took 3 commands:  (ignore the history numbers)
```

 2060  git clone git@github.com:iheanyi/bandcamp-dl.git
 2061  cd bandcamp-dl/
 2064  sudo python3 setup.py install
```

**Comment by bernard-crnkovic** [comment]
> Ok, your results helped me, and is now working. any idea why it stopped working?
> 
> BTW, only took 3 commands: (ignore the history numbers)
> 
> ```
> 
>  2060  git clone git@github.com:iheanyi/bandcamp-dl.git
>  2061  cd bandcamp-dl/
>  2064  sudo python3 setup.py install
> ```

my guess would be that fixed commit that was made yesterday hasn't yet made its way to PyPi as a new version.
I guess a reason for the error was some change in Bandcamp website DOM (bs4 is the parser used in this project as far as I can tell).

EDIT:
A-ha!
[My hunch was right](https://github.com/iheanyi/bandcamp-dl/issues/166)

**Comment by Evolution0** [comment]
Yeah I merged the fixes in among some other things finally, no pypi release though as I can't thoroughly test before release and my PC is out of commision currently.
