### ISSUE TITLE
Non existing directory in --base-dir produces crash

### ISSUE THREAD

**Issue by seth--** [Evolution0/bandcamp-dl#17]
```
[/tmp/bandcamp-dl/bandcamp-dl]; python2 bandcamp-dl.py http://realfaction.bandcamp.com/album/planet-pulse-deluxe-edition --base-dir=/does-not-exist/
Traceback (most recent call last):
  File "bandcamp-dl.py", line 65, in <module>
    bandcamp_downloader.start(album)
  File "/tmp/bandcamp-dl/bandcamp-dl/BandcampDownloader.py", line 26, in start
    self.download_album(album)
  File "/tmp/bandcamp-dl/bandcamp-dl/BandcampDownloader.py", line 56, in download_album
    filename = self.template_to_path(track_meta)
  File "/tmp/bandcamp-dl/bandcamp-dl/BandcampDownloader.py", line 34, in template_to_path
    path = u"{0}/{1}.{2}".format(self.directory, path, "mp3")
AttributeError: BandcampDownloader instance has no attribute 'directory'
```

The problem seems to be here: https://github.com/iheanyi/bandcamp-dl/blob/f54a92a6333648681322fc3268b6a648fa30c8a0/bandcamp-dl/BandcampDownloader.py#L18
It just doesn't handle the directory not existing

**Comment by iheanyi** [comment]
I'll fix that, good looks.

**Comment by ajudator** [comment]
I think it is still happening... Even with up to date bandcamp-downloader and dependencies, you still get the AtributeError when setting the output to a not existent/to-be created folder. I don't really have any experience, but I'm writing this willing to help (and in case someone as n00b as me face this error)

> sudo pip install -U bandcamp-downloader
> Requirement already up-to-date: bandcamp-downloader in /usr/local/lib/python2.7/dist-packages
> Requirement already up-to-date: mutagen>=1.31 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: ply==3.4 in /usr/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: wgetter>=0.6 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: lxml>=3.5.0 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: slugify==0.0.1 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: slimit>=0.8.1 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: docopt>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)
> Requirement already up-to-date: beautifulsoup4>=4.4.1 in /usr/local/lib/python2.7/dist-packages (from bandcamp-downloader)

and after a 

> bandcamp-dl --base-dir=/NonExistingDirectory/ https://bandcamp.anything

you get

> Starting download process.
> Traceback (most recent call last):
>   File "/usr/local/bin/bandcamp-dl", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp_dl.py", line 64, in main
>     bandcamp_downloader.start(album)
>   File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/BandcampDownloader.py", line 27, in start
>     self.download_album(album)
>   File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/BandcampDownloader.py", line 57, in download_album
>     filename = self.template_to_path(track_meta)
>   File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/BandcampDownloader.py", line 35, in template_to_path
>     path = u"{0}/{1}.{2}".format(self.directory, path, "mp3")
> AttributeError: BandcampDownloader instance has no attribute 'directory'

Buut I found no trouble in bypassing (sorry if I'm mistaking something, I don't have any experience with python and very little linux knowledge) by setting as output a already existent folder. You get the music you wanted in a /ExistingFolder/Artist/TheAlbum/ :))

sorry if isn't helpful :/

**Comment by Evolution0** [comment]
Still an existing bug, fixing.

Edit: Fixed, added to Python 3 fork.
