### ISSUE TITLE
Download Quality

### ISSUE THREAD

**Issue by Alcross888** [Evolution0/bandcamp-dl#174]
Does this only download paid tracks? Does it download WAV tracks for free?

**Comment by obbardc** [comment]
default seems to be 128kbps MP3 :(

**Comment by Evolution0** [comment]
Only freely available content currently, at some point I would like for users to be able to login so they can batch download their purchased content.

Bitrate and format is dictated by whatever Bandcamp's preview format is.

**Comment by Alcross888** [comment]
Thank you for letting me know. God bless

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
