### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'string'

### ISSUE THREAD

**Issue by phoe** [Evolution0/bandcamp-dl#175]
**Python version:**  3.8.6

**Bandcamp-dl version:** `bandcamp_downloader-0.0.8.post12-py3-none-any.whl` installed from pip3 on debian sid

**Bancamp-dl options:**  none

**url:**  none

**options:**  none

**Describe the issue:**
-------------------------

```
$ bandcamp-dl
Traceback (most recent call last):
  File "/home/phoe/.local/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/home/phoe/.local/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/home/phoe/.local/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/home/phoe/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/home/phoe/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/home/phoe/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by Susko3** [comment]
Looks like pypi has the old version; the latest version built from the source is bandcamp-dl 0.0.9-01

I suggest you [install it from the source](https://github.com/iheanyi/bandcamp-dl#from-source) if you need it to work. The version 0.0.9-01 (latest from source) works fine for me.

**Comment by phoe** [comment]
The releases page at https://github.com/iheanyi/bandcamp-dl/releases mentions no `0.0.9` - perhaps that is the reason why it hasn't been picked up.

**Comment by 97997** [comment]
> 
> 
> Looks like pypi has the old version; the latest version built from the source is bandcamp-dl 0.0.9-01
> 
> I suggest you [install it from the source](https://github.com/iheanyi/bandcamp-dl#from-source) if you need it to work. The version 0.0.9-01 (latest from source) works fine for me.

i'm using 0.0.9-01 (latest from source) and i'm still getting the same error with all albums

**Comment by sumsare** [comment]
I installed it from source but either it didn't update correctly (cos fuck knows with command-line programs, it might have made a duplicate program somewhere else and since it doesn't say where, how would I know) or 0.0.9 doesn't exist (as the latest on /releases is 0.0.8-12)

**Comment by ajudator** [comment]
hi! i was getting the same error showed above, and uninstalling the old version and installing  the latest version built from source (obtained via the link in the main page here in github) made things work here. i also had to point the `python` command to use `python3` in the meanwhile, because bandcamp-dl was using the version provided by `python`, and in my case that was 2.7.something.

in sum:

```
pip3 uninstall bandcamp-downloader
cd /WhereYouExtractedTheZIP
[optional] sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
python setup.py install
```

**Comment by 97997** [comment]
> 
> 
> hi! i was getting the same error showed above, and uninstalling the old version and installing the latest version built from source (obtained via the link in the main page here in github) made things work here. i also had to point the `python` command to use `python3` in the meanwhile, because bandcamp-dl was using the version provided by `python`, and in my case that was 2.7.something.
> 
> in sum:
> 
> ```
> pip3 uninstall bandcamp-downloader
> cd /WhereYouExtractedTheZIP
> [optional] sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
> python setup.py install
> ```

this solution is working for me, thanks

**Comment by bt2901** [comment]
A slightly easier way to install from source is running
```
pip install git+https://github.com/iheanyi/bandcamp-dl --upgrade
```

**Comment by sumsare** [comment]
> A slightly easier way to install from source is running
> 
> ```
> pip install git+https://github.com/iheanyi/bandcamp-dl --upgrade
> ```

I need to install git and put it in PATH, how do I do that?

**Comment by Susko3** [comment]
> I need to install git and put it in PATH, how do I do that?

https://github.com/git-guides/install-git

**Comment by sumsare** [comment]
> > I need to install git and put it in PATH, how do I do that?
> 
> https://github.com/git-guides/install-git

Thank you, this worked for me :)

**Comment by Evolution0** [comment]
Pypi is updated manually, so I have to build a wheel and a source release and upload it; something I haven't done in some time but should probably soon just to have an unbroken release available.

**Comment by DiameterEffect** [comment]
> Looks like pypi has the old version; the latest version built from the source is bandcamp-dl 0.0.9-01
> 
> I suggest you [install it from the source](https://github.com/iheanyi/bandcamp-dl#from-source) if you need it to work. The version 0.0.9-01 (latest from source) works fine for me.

this worked for me!

**Comment by iheanyi** [comment]
Okay y'all, I've gone ahead and updated the version on PyPI. I'll make an issue to automate updating the version in PyPI so whenever a new release is cut, it will automatically update it to PyPI. Sorry for any inconvenience with this. 😅  Would love for folks to try and install this and try it out and confirm that it works as expected now.

**Comment by Susko3** [comment]
Installed latest version from PyPI

Pip reported version as `0.0.9.post1`

bandcamp-dl --version `0.0.9-01`

Downloading works without errors!

**Comment by iheanyi** [comment]
Closing this issue given that I think the latest version is uploaded now. Please re-open if it doesn't work
