### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by crophyrus** [Evolution0/bandcamp-dl#183]
it just keep popping up. i don't know which step did i miss

**Comment by Evolution0** [comment]
Python version?
Bandcamp-dl version?
OS?
Command you tried to run?

**Comment by E-H-Q** [comment]
I'm having this issue too.

Python version: 3.6.9
bandcamp-dl version: 0.0.10
OS: Ubuntu 18.04.5
Command run: `bandcamp-dl https://mareux.bandcamp.com/album/predestiny-ep`

I've attached a screen shot of the errors its giving me:
![2021-05-23-031827_925x172_scrot](https://user-images.githubusercontent.com/36213914/119254782-9298fe80-bb75-11eb-90cc-ca8582242436.png)

**Comment by Evolution0** [comment]
The version of python you listed and the version shown in the error are different, that tells me that bandcamp-dl did not install under Python 3 on your system and is bugging out because type hints were added in 3.5 and its running under Python 2.7.

Did you install using pip3?

**Comment by E-H-Q** [comment]
Ah, rather embarrassed that I missed something that obvious. Just re-installed using pip3 and now it works like a charm! 
Thank you very much for your help!
