### ISSUE TITLE
Unable to download track

### ISSUE THREAD

**Issue by loscil06** [Evolution0/bandcamp-dl#196]
**Python version:**  
3.9
**Bandcamp-dl version:**
0.0.9-01
**Bancamp-dl options:**  
None
**url:**  
https://saintpepsi.bandcamp.com/track/we-can-make-it 
**options:**  
None
**Describe the issue:**
-------------------------
bandcamp-dl is unable to download content:
```
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/__main__.py", line 92, in main
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcamp.py", line 70, in parse
TypeError: strptime() argument 1 must be str, not None
```

**Comment by Evolution0** [comment]
Should be using the latest which is 0.0.12 not 0.0.9-01.

Edit: Looks like its an issue with this track in the latest too, there is either no release date tied to it in both the places I check or they changed the format again.

**Comment by Evolution0** [comment]
Alright go ahead and update, I just pushed a release with another fallback date in case a track doesn't have one in the usual places.

**Comment by loscil06** [comment]
> Alright go ahead and update, I just pushed a release with another fallback date in case a track doesn't have one in the usual places.

You're God-sent, thanks a lot!
