### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by coffseducation** [Evolution0/bandcamp-dl#206]
**Describe the bug**

**To Reproduce**
Command to reproduce the behavior:
bandcamp-dl
```

```

**Expected behavior**
the bandcamp album downloads

**Logs**
Traceback (most recent call last):
  File "/home/anarcho/.local/bin/bandcamp-dl", line 5, in <module>
    from bandcamp_dl.__main__ import main
ModuleNotFoundError: No module named 'bandcamp_dl
```
bandcamp-dl --debug
Traceback (most recent call last):
  File "/home/anarcho/.local/bin/bandcamp-dl", line 5, in <module>
    from bandcamp_dl.__main__ import main
ModuleNotFoundError: No module named 'bandcamp_dl'
``
If possible after running the command with the --debug option.

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-1003-lowlatency (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 31.2 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 530
Manufacturer: Dell Inc.
Product Name: Precision 5720 AIO

**Additional context**
Change in how python is handled in 23.04???

**Comment by itsxaos** [comment]
Did you update your Python?
Looks like Ubuntu 23.04 updated Python to v3.11, so maybe that broke your bandcamp-dl install.
Try re-installing bandcamp-dl via pip (or however you installed it before), that should fix it.
I had to reinstall the package after updating, works fine again now.

**Comment by coffseducation** [comment]
Yes Python is up to date. There is also something about evn variables and pipx is now recommened.
Re-install or pipx made no difference.
Thanks for the reply!

**Comment by Evolution0** [comment]
I haven't had any issues in 3.11 so far and its what I currently test and develop on so this is almost definitely an issue with the distro.

I was made aware of a change that was made in Ubuntu with the update where you cannot install packages directly with pip anymore* unless you install a separate version of Python (or use a venv), how are you installing bandcamp-dl?

* Unless using the `--break-system-packages` (Obviously frowned upon by its very name) arg.

Is it possible that old installation of bandcamp-dl is still in your path, and the pipx installation isn't being picked up?
