### ISSUE TITLE
Better error message, if download is not available (incorrect link)

### ISSUE THREAD

**Issue by gorgobacka** [Evolution0/bandcamp-dl#214]
If to valid album is detected (e.g. the album is not available anymore), the app breaks and the user only sees an exception.

E.g. try to download https://esotericmusic.bandcamp.com/album/creator-ease-back

It would be great, if the user would see a message like: "no valid link provided".

**Comment by Evolution0** [comment]
404s are now caught in the next update with the user being informed that the requested media is not available at the provided URL.
