### ISSUE TITLE
Exception when using --no-slugify

### ISSUE THREAD

**Issue by nrlquaker** [Evolution0/bandcamp-dl#222]
**Describe the bug**
Running with `--no-slugify` throws an Exception

**To Reproduce**
Command to reproduce the behavior:
bandcamp-dl --no-slugify https://severoth.bandcamp.com/album/by-the-way-of-light
```
https://severoth.bandcamp.com/album/by-the-way-of-light
```

**Expected behavior**
Should not throw an Exception if running with `--no-slugify`.

**Logs**
Most if not always you will get some kind of output explaining the issue, post it:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_2/libexec/lib/python3.12/site-packages/bandcamp_dl/__main__.py", line 114, in main
    bandcamp_downloader.start(album)
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_2/libexec/lib/python3.12/site-packages/bandcamp_dl/bandcampdownloader.py", line 55, in start
    self.download_album(album)
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_2/libexec/lib/python3.12/site-packages/bandcamp_dl/bandcampdownloader.py", line 142, in download_album
    filepath = self.template_to_path(track_meta, self.config['--ascii-only'], self.config['--ok-chars'],
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_2/libexec/lib/python3.12/site-packages/bandcamp_dl/bandcampdownloader.py", line 77, in template_to_path
    path = path.replace("%{trackartist}", track['artist'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: replace() argument 2 must be str, not None
```

If possible after running the command with the --debug option.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.4.1 (23E224)
 - Python Version 3.12.3

**Additional context**

**Comment by Evolution0** [comment]
Looks like this is related to #224 as in its caused by #212 and `trackartist` being `None`.

**Comment by tanshoku** [comment]
Fixed this by changing the following lines in bandcampdownloader.py

```
75a76
>
77c78,81
<             path = path.replace("%{trackartist}", track['artist'])
---
>             if str(track['artist']) == "None":
>                 path = path.replace("%{trackartist}", track['albumartist'])
>             else:
>                 path = path.replace("%{trackartist}", track['artist'])
```

im not sure why `if track['artist'] == "None":` doesn't work since im not a python programmer, so i just used `str()` to get around that.

**Comment by Evolution0** [comment]
> Fixed this by changing the following lines in bandcampdownloader.py
> 
> ```
> 75a76
> >
> 77c78,81
> <             path = path.replace("%{trackartist}", track['artist'])
> ---
> >             if str(track['artist']) == "None":
> >                 path = path.replace("%{trackartist}", track['albumartist'])
> >             else:
> >                 path = path.replace("%{trackartist}", track['artist'])
> ```
> 
> im not sure why `if track['artist'] == "None":` doesn't work since im not a python programmer, so i just used `str()` to get around that.

This is due to the fact that `None` is essentially Python's `Null`, its not a string as its quite literally nothing it just gets converted to one later on when getting set as the artist name.

In this case since you aren't operating on values or actually checking for equality you would go about it differently. In Python everything is an object and that includes None so you want to check identity, rather than equality. In this case you would do: `if track['artist'] is None` or if readability isn't a concern and you just care if its `None`/`False`: `if not track['artist']:`

For now I'll add the check for this but I really need to handle this in the code that populates the track info dict.

**Comment by Evolution0** [comment]
Tentatively fixed with f2d24825bb0f72a51d8af17eaf257e40b6b0e223

**Comment by nrlquaker** [comment]
Can you please release new version and update brew formula?

**Comment by Evolution0** [comment]
> Can you please release new version and update brew formula?

I have no control over the brew formula, its maintained by someone else.

However from what I can tell by default it relies on the Pypi package which won't be updated till I get confirmation that the last few recent issues are cleared away. You do seem to have the option to install with `bandcamp-dl --HEAD` though which appears to grab the latest git release, that should work.

**Comment by nrlquaker** [comment]
@Evolution0, ok I can update brew formula, but please bump the version and create a github release.

**Comment by Evolution0** [comment]
> @Evolution0, ok I can update brew formula, but please bump the version and create a github release.

All set

**Comment by nrlquaker** [comment]
Oh, homebrew now uses Pypi package instead of GitHub release. Will wait when it will be released to update formula then.
