### ISSUE TITLE
Download crashes `'bandcamp_dl.config' has no attribute 'init_config'`

### ISSUE THREAD

**Issue by jneidel** [Evolution0/bandcamp-dl#232]
**Describe the bug**
Crashes on download.

**To Reproduce**
Downloading anything throws this error.
```
bandcamp-dl "https://jpegmafia.bandcamp.com/album/i-lay-down-my-life-for-you"
```

**Expected behavior**
Don't crash :joy:

**Logs**
```
Traceback (most recent call last):
  File "/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/bandcamp_dl/__main__.py", line 89, in main
    arguments = config.init_config(parser)
                ^^^^^^^^^^^^^^^^^^
AttributeError: module 'bandcamp_dl.config' has no attribute 'init_config'
```

**Desktop:**
 - OS: Arch
 - Python 3.12.4
 - bandcamp-dl 0.0.15 (latest git)

**Comment by kjake** [comment]
From my testing, this line isn't needed, and I deleted it from my PR: https://github.com/iheanyi/bandcamp-dl/pull/234

**Comment by ghost** [comment]
Having this issue as well, has there been any fix..?

**Comment by kjake** [comment]
The PR has merged, so I think this can be closed @Evolution0
