### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [Evolution0/bandcamp-dl#235]
👋 it has been more than two years since last release, and it would be good to cut a new release (the HEAD build has some issue for me as in https://github.com/iheanyi/bandcamp-dl/issues/232). 

Seeing some regression run failure for 0.0.15

```
/opt/homebrew/Cellar/bandcamp-dl/0.0.15_3/libexec/lib/python3.12/site-packages/bandcamp_dl/utils/unicode_slugify.py:84: SyntaxWarning: invalid escape sequence '\s'
  new = re.sub('[%s\s]+' % space_replacement, space_replacement, new)
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_3/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_3/libexec/lib/python3.12/site-packages/bandcamp_dl/__main__.py", line 76, in main
    config = init_config(arguments)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.15_3/libexec/lib/python3.12/site-packages/bandcamp_dl/utils/config.py", line 61, in init_config
    elif first_run is False:
         ^^^^^^^^^
UnboundLocalError: cannot access local variable 'first_run' where it is not associated with a value
```

relates to https://github.com/Homebrew/homebrew-core/pull/183094

**Comment by Evolution0** [comment]
Soon, it was completely broken for a while and recently went through some big changes. As of now it works and one of the most pressing issues is fixed so its usable but I want to comb through the issues and see if there is any low hanging fruit and ensure that the recent changes work for everyone (I don't have the time personally to test across all OSes)

**Comment by christatedavies** [comment]
Yay, my `bandcamp-dl` is fixed! Thanks guys, everyone who put work into this

**Comment by branchv** [comment]
FYI, looks like `v0.0.16` is missing from PyPI due to the publish job failing: https://github.com/iheanyi/bandcamp-dl/actions/runs/10818854657/job/30015403909

**Comment by Evolution0** [comment]
> FYI, looks like `v0.0.16` is missing from PyPI due to the publish job failing: https://github.com/iheanyi/bandcamp-dl/actions/runs/10818854657/job/30015403909

It's never worked due to the fact that while I can create actions I can't edit repo settings to add secrets and such for credentials to push releases to PyPI as I'm not the owner just the maintainer.

I can manually do it though and will soon after fixing some minor things, in the mean time you can `pip install` the `.whl` file in the tagged release, just update urllib3 to the latest version after.

**Comment by Evolution0** [comment]
Done, current PyPI release has only one minor change over tagged release relating to urllib3 version to avoid dependency issues.
