### ISSUE TITLE
ImportError: cannot import name 'create_urllib3_context' from 'urllib3.util'

### ISSUE THREAD

**Issue by ghost** [Evolution0/bandcamp-dl#237]
Bug Description
First moment i was trying to download, bandcamp-dl is returned with "AttributeError" errors...
Reintalled and updated python, now it fails to download with ImportError;
The program worked before.

To Reproduce
Command to reproduce the behavior:
`bandcamp-dl --base-dir=Music/Myfolder -e -f -k -u -o -r [any link]`

Expected behavior
Attempting to run the command will return the following error:

Logs
```
Traceback (most recent call last):
  File "/usr/bin/bandcamp-dl", line 5, in <module>
    from bandcamp_dl.__main__ import main
  File "/usr/lib/python3.12/site-packages/bandcamp_dl/__main__.py", line 27, in <module>
    from bandcamp_dl.bandcamp import Bandcamp
  File "/usr/lib/python3.12/site-packages/bandcamp_dl/bandcamp.py", line 9, in <module>
    from urllib3.util import create_urllib3_context
ImportError: cannot import name 'create_urllib3_context' from 'urllib3.util' (/usr/lib/python3.12/site-packages/urllib3/util/__init__.py)
```

Desktop:
    OS: Arch Linux
    Version: 6.6.49-l-lts
    Python Version: 3.12.5-1

**Comment by Evolution0** [comment]
Which version of urllib is installed? `pip freeze | grep urllib`

**Comment by SinfulChaser** [comment]
urllib3 = 1.26.20

**Comment by Evolution0** [comment]
> urllib3 = 1.26.20

Upgrade to 2.x.x if possible.

**Comment by jneidel** [comment]
I have the same problem.

Not a python dev, but shouldn't `urllib3` be declared as a dependency in `pyproject.toml`? Then you can declare a v2 requirement and have the app fail gracefully.

**Comment by jneidel** [comment]
@SinfulChaser I addressed the issue in the arch pkg:
`yay -S bandcamp-dl-git`

**Comment by SinfulChaser** [comment]
@jneidel 
The problem was fixed, it is working correctly now.

**Comment by Evolution0** [comment]
> I have the same problem.
> 
> Not a python dev, but shouldn't `urllib3` be declared as a dependency in `pyproject.toml`? Then you can declare a v2 requirement and have the app fail gracefully.

Yes, some quirks slipped through between PRs, I blame the lack of automated testing.
