### ISSUE TITLE
Open tab URL

### ISSUE THREAD

**Issue by elCharlot** [Evolution0/bandcamp-dl#243]
Hi !
Amazing script, very useful, and I was wondering if there was a way to add in the commands the otpion to retrieve the url of open tab in browser ?

thanks a lot

**Comment by Evolution0** [comment]
Overcomplicated for a minor feature, every browser is different, every OS handles running processes different, would likely pull in a bunch of unrelated dependencies. This is better handled by a browser extension firing off bandcamp-dl as an external utility.

**Comment by elCharlot** [comment]
Thanks a lot for taking time to answer !
