### ISSUE TITLE
download fails?

### ISSUE THREAD

**Issue by yahyah2** [Evolution0/bandcamp-dl#32]
C:\Users\User\Desktop\bandcamp-dl-master\bandcamp-dl>bandcamp-dl.py https://hot
flashheatwave.bandcamp.com/album/neapolitan
unknown url type: //popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=09bd9
d2a0c4b1777c8048cf4d5d27b16&id=2769757913&stream=1&ts=1444516310.0
Downloading failed..

**Comment by rdlmda** [comment]
I get the same error here

**Comment by JackRonan** [comment]
This is due to wget not using 'http:' in front of the address before it tries to download, to fix I just added a simple concatenation that prefaces the url with 'http:'  on line 68 of BandcampDownloader.py.

> ```
>            tmp_file = wgetter.download(('http:')+(track['url']), outdir=dirname)
> ```

**Comment by Ristellise** [comment]
#35 
did a small fix to fix issues like this above.

**Comment by Ristellise** [comment]
aslo credited @jackronan for the fix.

**Comment by iheanyi** [comment]
Awesome, thanks for this!

**Comment by iheanyi** [comment]
Added a cleaner version of the fix, fixed now.
