### ISSUE TITLE
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

### ISSUE THREAD

**Issue by rdlmda** [Evolution0/bandcamp-dl#33]
Downloaded  #83b409a, run `pip install -r requirements.txt`, I'm getting the error:

> bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

Solution:

```
# apt-get install libxslt1-dev libxml2 python-dev
# pip install --upgrade lxml
```

**Comment by rdlmda** [comment]
Now I am still seeing issue #32, I suppose it's unrelated.

**Comment by iheanyi** [comment]
Updated the dependencies, thanks!

**Comment by liusha250c1** [comment]
Instead of using lxml use html.parser, you can use this piece of code:

soup = BeautifulSoup(html, 'html.parser')
