### ISSUE TITLE
Couldn't download album art.

### ISSUE THREAD

**Issue by makamys** [Evolution0/bandcamp-dl#37]
I printed out `r.text` and `self.soup` in `Bandcamp.parse()`, and found that in `self.soup` the html gets cut short, while `r.text` contains the full html.

Using BeautifulSoup with `html5lib` instead of `lxml` fixes the issue.

I'm using python 2.7.6 on Windows 7, by the way.

**Comment by iheanyi** [comment]
@KunaiFire - Problem with using html5lib instead of lxml is that it's waaaaaay slower. :/ So that's a tradeoff. I'll look into this more later, thanks for openign this issue though.

**Comment by Evolution0** [comment]
Apparently this sometimes happens on certain machines under certain conditions and is a pain to reproduce.

For me there is a difference of only one line and that is at the very bottom of the pages source and its a comment which is a known issue (Comments outside of \<html>\</html> being truncated) and pretty much unimportant.

If its really an issue html.parser is also an option and not nearly as slow as html5lib. it also doesn't require another module to be installed.

It might actually be a good idea too.. seeing as installing lxml can be a pain for some, using html.parser would lead to a smoother install.

Edit: I'm not noticing much of a speed difference with html.parser, think I'm going to remove the lxml requirement seeing as BeautifulSoup4 will automatically import lxml if the user installs it, that way its not "required" but can be used for a speed boost if users so desire.

Strangely enough if I set the parser to html.parser it works fine, set to lxml it works fine, and set to html5lib as well. But if you let it choose automatically (By not setting it manually) even if it uses one of the previously fine working parsers it will *still* not find the album art url and it does not explain why.

Interesting thing, stepping through the code in my debugger its clear that the content that comes back indeed has the tralbumArt div with the img url in it yet `url = self.soup.find(id='tralbumArt').find_all('img')[0]['src']` returns nothing.

In the end I'm just going to go with a good ole' try/except, that seems to work fine.

As this boils down to a parser issue and is something that is out of our control I'm closing this, hopefully my new method will at least try to reduce the possibility of this happening.
