### ISSUE TITLE
Lyrics in tags

### ISSUE THREAD

**Issue by AlessandroAnnini** [Evolution0/bandcamp-dl#49]
How about downloading lyrics stright into the mp3 tag?
I think this could be interesting for really a lot of people

Thank you very much!

**Comment by iheanyi** [comment]
@sun2rise - Unfortunately that goes out of the scope of this project, especially considering that most albums sold on Bandcamp are by indie artists, not as easy to find lyrics for them. Thanks for the suggestion though!
