### ISSUE TITLE
Service Unavailable 503 

### ISSUE THREAD

**Issue by manishkshwh** [Evolution0/bandcamp-dl#55]
Have you guys seen this before ?

C:\Python27\Scripts\bandcamp-dl\bandcamp_dl>bandcamp_dl.py -f https://dynamitemo
tel.bandcamp.com/
Starting download process.
Accessing track 1 of 12
HTTP Error 503: Service Unavailable
Downloading failed..

Let me know if you could give me a lead on this. I have tried several times.

**Comment by Evolution0** [comment]
I can't reproduce this.

Generally a 503 means the server is under heavy load, I'm assuming it was just a period of high traffic on BC that caused this.
