### ISSUE TITLE
problems installing bandcamp-dl on windows

### ISSUE THREAD

**Issue by shadoxxhd** [Evolution0/bandcamp-dl#56]
i run the command pip install bandcamp-downloader and got this:
http://pastebin.com/wDNjBYWf

it seems like i have to install libxml2 and libxslt, but I'm not sure how. i dropped the required files inside directory inside %PATH%, but I still get the same error (apparently, xslt-config isn't included in the windows release of libxslt)

also, why is the installer calling a c compiler?

**Comment by berrythesoftwarecodeprogrammar** [comment]
clone the git repository. the pip version is outdated

**Comment by Bendito999** [comment]
What I had to do was download lxml from here http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml Then install it with

`pip install lxml-3.6.4-cp27-cp27m-win_amd64.whl`

**Comment by Evolution0** [comment]
This is not a bandcamp-dl specific error/issue.

It happens when you don't have the proper setup to compile a pip package (some require a compiler), use the pre-compiled wheels on http://www.lfd.uci.edu/~gohlke/pythonlibs/ in this case as Bendito999 suggested.
