### ISSUE TITLE
Unable to install on OS X 10.11.3

### ISSUE THREAD

**Issue by Staindk** [Evolution0/bandcamp-dl#58]
Hi,

trying to install using different versions of python (3.5 didn't work, tried 2.7 and got a bit further I think) and getting nowhere. [This window](https://i.imgur.com/QP4YQiV.jpg) keeps popping up but I'm not keen on downloading all of Xcode just for this command-line app (probably won't fix my problem anyhow).

Terminal's version of the issue is as follows (two of the bold parts being what showed in red in terminal, other bold/italics parts just interpreted by github and I did not want to find and escape it all):

my-MacBook-Pro:bandcamp-dl-master username$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4==4.4.1 in /Library/Python/2.7/site-packages/beautifulsoup4-4.4.1-py2.7.egg (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Collecting lxml==3.5.0 (from -r requirements.txt (line 3))
  Using cached lxml-3.5.0.tar.gz
Collecting mutagen==1.31 (from -r requirements.txt (line 4))
Requirement already satisfied (use --upgrade to upgrade): ply==3.4 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Collecting requests==2.8.1 (from -r requirements.txt (line 6))
  Using cached requests-2.8.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): slimit==0.8.1 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Collecting slugify==0.0.1 (from -r requirements.txt (line 8))
Requirement already satisfied (use --upgrade to upgrade): wgetter==0.6 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Building wheels for collected packages: lxml
  Running setup.py bdist_wheel for lxml ... error
  Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;**file**='/private/var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-build-aK_JAK/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" bdist_wheel -d /var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/tmp5IQUOfpip-wheel- --python-tag cp27:
  Building lxml version 3.5.0.
  Building without Cython.
  Using build configuration of libxslt 1.1.28
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.6-intel-2.7
  creating build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/**init**.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/_elementpath.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/builder.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/cssselect.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/doctestcompare.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/ElementInclude.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/sax.py -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/usedoctest.py -> build/lib.macosx-10.6-intel-2.7/lxml
  creating build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/__init__.py -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  creating build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/**init**.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/builder.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/clean.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/defs.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/diff.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/formfill.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/html5parser.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/soupparser.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
  creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron
  copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron
  copying src/lxml/lxml.etree.h -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.6-intel-2.7/lxml
  copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/config.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.6-intel-2.7/lxml/includes
  creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources
  creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/rng
  copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/rng
  creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
  copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
  creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
  running build_ext
  building 'lxml.etree' extension
  creating build/temp.macosx-10.6-intel-2.7
  creating build/temp.macosx-10.6-intel-2.7/src
  creating build/temp.macosx-10.6-intel-2.7/src/lxml
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.6-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace
  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
  Compile failed: command '/usr/bin/clang' failed with exit status 1
  creating var
  creating var/folders
  creating var/folders/g_
  creating var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn
  creating var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T
  cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/xmlXPathInithEjNFb.c -o var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/xmlXPathInithEjNFb.o
  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.

---

  Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
  Perhaps try: xcode-select --install

---

  error: command '/usr/bin/clang' failed with exit status 1

---

  **Failed building wheel for lxml**
  Running setup.py clean for lxml
Failed to build lxml
Installing collected packages: lxml, mutagen, requests, slugify
  Running setup.py install for lxml ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;**file**='/private/var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-build-aK_JAK/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-79JInE-record/install-record.txt --single-version-externally-managed --compile:
    Building lxml version 3.5.0.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.6-intel-2.7
    creating build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/**init**.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/_elementpath.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/builder.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/cssselect.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/doctestcompare.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/ElementInclude.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/pyclasslookup.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/sax.py -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/usedoctest.py -> build/lib.macosx-10.6-intel-2.7/lxml
    creating build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/__init__.py -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    creating build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/**init**.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/_diffcommand.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/_html5builder.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/_setmixin.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/builder.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/clean.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/defs.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/diff.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/ElementSoup.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/formfill.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/html5parser.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/soupparser.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    copying src/lxml/html/usedoctest.py -> build/lib.macosx-10.6-intel-2.7/lxml/html
    creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron
    copying src/lxml/isoschematron/__init__.py -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron
    copying src/lxml/lxml.etree.h -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/lxml.etree_api.h -> build/lib.macosx-10.6-intel-2.7/lxml
    copying src/lxml/includes/c14n.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/config.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/dtdvalid.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/etreepublic.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/htmlparser.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/relaxng.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/schematron.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/tree.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/uri.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xinclude.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlerror.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlparser.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xmlschema.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xpath.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/xslt.pxd -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/etree_defs.h -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    copying src/lxml/includes/lxml-version.h -> build/lib.macosx-10.6-intel-2.7/lxml/includes
    creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources
    creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/rng
    copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/rng
    creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
    copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl
    creating build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.macosx-10.6-intel-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
    running build_ext
    building 'lxml.etree' extension
    creating build/temp.macosx-10.6-intel-2.7
    creating build/temp.macosx-10.6-intel-2.7/src
    creating build/temp.macosx-10.6-intel-2.7/src/lxml
    /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/include/libxml2 -Isrc/lxml/includes -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.macosx-10.6-intel-2.7/src/lxml/lxml.etree.o -w -flat_namespace
    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
    Compile failed: command '/usr/bin/clang' failed with exit status 1
    cc -I/usr/include/libxml2 -I/usr/include/libxml2 -c /var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/xmlXPathInit6au2LF.c -o var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/xmlXPathInit6au2LF.o
    xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
    *********************************************************************************
    Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
    Perhaps try: xcode-select --install
    *********************************************************************************
    error: command '/usr/bin/clang' failed with exit status 1

```
----------------------------------------
```

**Command "/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c "import setuptools, tokenize;**file**='/private/var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-build-aK_JAK/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-79JInE-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/g_/y6drsh013k7b_kmk8n8htry00000gn/T/pip-build-aK_JAK/lxml/**

---

Not sure what to try next, maybe I messed up how wheels is installed because I tried to install pip onto osx's native/preinstalled version of python (as the pip site says not to do)?

**Comment by Mixbo-zz** [comment]
You absolutely need the command line tools on OSX. I can't think of any workaround.

**Comment by Evolution0** [comment]
No way around it however you have the wrong idea, you only download the command line tools not XCode in its entirety.
