### ISSUE TITLE
bandcamp-dl: command not found

### ISSUE THREAD

**Issue by arielelkin** [Evolution0/bandcamp-dl#59]
Just installed on OS X 10.11.4 following instructions on README file, I get this output:

```
$ bandcamp-dl http://bandcampurl.com/
-bash: bandcamp-dl: command not found
```

**Comment by arielelkin** [comment]
`pip install bandcamp-downloader` reinstalled properly.

**Comment by iheanyi** [comment]
Glad to hear, sorry for not replying to this in a timely fashion.
