### ISSUE TITLE
Ascii codec error

### ISSUE THREAD

**Issue by isaachinman** [Evolution0/bandcamp-dl#62]
It doesn't look like this repo is maintained anymore, but just in case it is, I've gotten the following error (reproducible):

```
'ascii' codec can't decode byte 0xe7 in position 9: ordinal not in range(128)
Downloading failed..
```

The album in question is here: `https://dohits.bandcamp.com/album/do-hits-vol-4`. It fails consistently on the second track, which has a Chinese character in it.

**Comment by iheanyi** [comment]
Sorry, I'll take a look at it. Could be an encoding issue.

**Comment by isaachinman** [comment]
No problem. I really appreciate and make use of this repo, cheers!

**Comment by Mixbo-zz** [comment]
@isaachinman are you using the latest version? This looks a lot like an issue I fixed in march.

Original PR: https://github.com/iheanyi/bandcamp-dl/pull/52

**Comment by Evolution0** [comment]
It was indeed broken, track name needed to be encoded. Fixed in my fork, should be in master branch soon-ish.
