### ISSUE TITLE
Impossible to run as is, incorrect instructions in README.md or Python is messing around

### ISSUE THREAD

**Issue by exoloner** [Evolution0/bandcamp-dl#65]
Windows 7 32bits
Python 3.5.2 
Path + C:\Users\imunoz\AppData\Local\Programs\Python\
and...
pip install -r requirements.txt
goes in...
[ERRORS.txt](https://github.com/iheanyi/bandcamp-dl/files/486994/ERRORS.txt)

**Comment by mutabledevotions** [comment]
Can confirm.

[BandcampError.txt](https://github.com/iheanyi/bandcamp-dl/files/504088/BandcampError.txt)

**Comment by Mixbo-zz** [comment]
Maybe this won't fix your issue, but I see you are both using python3 while this repo was created for python2.

**Comment by iheanyi** [comment]
Yeah...I was using Python 2 when this was created. I haven't had time to update it to Python 3.

**Comment by exoloner** [comment]
Correct! Can you pretty please change the " It requires the Python
interpreter, version 2.7+ " to " It requires the Python interpreter,
version <3 "
Thanks! thanks!

2016-10-04 22:00 GMT+02:00 Iheanyi Ekechukwu notifications@github.com:

**Comment by exoloner** [comment]
Anyway...we're on a dead-end, requires PIP, amb pip does not installs with
old versions of python due a PARANOID urllib3 SSL insecurity...

My god!  ...

python get-pip.py
[................]
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |################################| 71kB 612kB/s
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-8.1.2 setuptools-28.2.0 wheel-0.29.0
c:\users\imunoz\appdata\local\temp\tmpexkdz8\pip.zip\pip_vendor\requests\packag
es\urllib3\util\ssl_.py:122: InsecurePlatformWarning: A true SSLContext
object i
s not available. This prevents urllib3 from configuring SSL appropriately
and ma
y\* cause certain SSL connections to fail. You can upgrade to a newer
version of P*
_ython to solve this._ For more information, see
https://urllib3.readthedocs.org/e
n/latest/security.html#insecureplatformwarning.

D:>pip
"pip" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

This is getting worse than DLL hell precisely trying to avoid DLL hell...

2016-10-05 9:03 GMT+02:00 JaK threepixels exoloner@gmail.com:

**Comment by iheanyi** [comment]
Oh God. :x I'll have to make a note to update the README. And make a call for maintainers.

**Comment by exoloner** [comment]
Yes. Please, it would help a lot. Compulsory tools updating gonna kill the
software engineering.
.stay.safe.

**Comment by Evolution0** [comment]
ReadMe clarified. Python 3 update should be relatively soon. I have a working fork but I would like to add backwards compatibility to it (As much as I am against Python 3 hold-outs I understand the need) and maybe tweak the console output a bit.
