### ISSUE TITLE
Flac

### ISSUE THREAD

**Issue by Pippone77** [Evolution0/bandcamp-dl#68]
Is It possibLe to downloadd flac verions?

**Comment by Evolution0** [comment]
As far as I know bandcamp-dl grabs the tracks from the same place as the bandcamp music player (Which is public), the FLAC downloads are private files behind a paywall. (Unless a free release? But I don't think it handles that.).

And obviously converting to FLAC would be silly.

Trying to bypass that paywall and get what you would normally pay for goes beyond being a bit annoying to the artist; it would be downright malicious and I doubt any of the contributors let alone the project owner would want to contribute to that.

tl;dr: No.

**Comment by iheanyi** [comment]
@Evolution0 Gave a good answer to this, closing this issue. :)
