### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by greymouser** [Evolution0/bandcamp-dl#69]
Looks like a missing dependency.

```
$ bandcamp-dl --help
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
  File "/usr/local/lib/python2.7/site-packages/bandcamp_dl/bandcamp_dl.py", line 42, in <module>
    from Bandcamp import Bandcamp
  File "/usr/local/lib/python2.7/site-packages/bandcamp_dl/Bandcamp.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

The workaround is simple enough:
```
$ pip install requests
$ bandcamp-dl --help
... (expected output)
```

**Comment by Evolution0** [comment]
You must have installed with setup.py, the dep is indeed missing from it (but is correctly listed in requirements and deps)

**Comment by greymouser** [comment]
I installed it as the docs stated -- `pip install bandcamp-downloader`.

It's worth to note that after I installed, pip let me know that there was a newer version of pip available. Other than that, nothing notable.

**Comment by Evolution0** [comment]
Yeah PyPI uses setup.py so when you pip install that is what it is using to know what dependencies are required and how to install it.
