### ISSUE TITLE
Dang it! Yours is better!

### ISSUE THREAD

**Issue by nonnymoose** [Evolution0/bandcamp-dl#72]
I created a shell script that performs the same function as bandcamp-dl, and I independently, without knowledge of your project, named it the same way. 
http://github.com/nonnymoose/bandcampdl
Do you mind? Or should I change the name? (Because yours _is_ better...)

**Comment by Evolution0** [comment]
I don't think it really matters, most people probably get bandcamp-dl from PyPI and its called bandcamp-downloader there anyway.

They are easy enough to differentiate as (afaik) we follow the naming convention of youtube-dl.

And anyone looking for the repo would know to search by python.

**Comment by nonnymoose** [comment]
@Evolution0 
He he... You were right about youtube-dl.
Thanks. I didn't think anybody would care (there are actually at least **three** bandcampdls), but as I've never talked to anyone about identical naming that was this precise before, I thought I'd get another person's opinion.
Thanks again, and really, yours is better. ;-)
