### ISSUE TITLE
Track, Artist, Album search

### ISSUE THREAD

**Issue by Evolution0** [Evolution0/bandcamp-dl#74]
Most definitely possible to add though it would be a separate component as it is essentially a frontend.

I have played around with it a bit and its quite easy to just append a search term to the search url, request it, and use BeautifulSoup to grab the element containing the result type (Artist, Album, Track) and url. Just not sure *how* I want to implement it yet as there is the possibility that a search wouldn't turn up an exact match.

Maybe print out the top 5 results by default and allow the user to then filter by type (and display more results)

Possibly as a separate repo.

**Comment by iheanyi** [comment]
🤔 I like this. What if we passed it in as a flag, which then would trigger a CLI for searching for the artists/albums and all that?

**Comment by Evolution0** [comment]
Something like: `bandcamp-dl --search="query"` or `bandcamp-dl -s query` (shorthand)?

It should be simple to import the search module into bandcamp_dl.py just like we do with bandcamp.py for the parsing with minimal changes to the main module (`if not album:` would need to change)

A nice thing is that it requires no additional overhead, we already use Requests and BeautifulSoup in the parser.

**Comment by Evolution0** [comment]
Pushed back, needs to be fleshed out more.

**Comment by Evolution0** [comment]
Work on this will be done in [bandcamp-cli](https://github.com/Evolution0/bandcamp-cli).
