### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by rapha8l** [Evolution0/bandcamp-dl#76]
Hi, after upgrading I get a (python 2.7)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 192: ordinal not in range(128) 

Maybe it could be due to some incompabilties with other libraries, I have this with pip list (sorry for the long list)  :
alabaster (0.7.8)
all (0.0.2)
alot (0.3.6)
ansible (2.2.0.0)
apt-p2p (0.1.5)
arandr (0.1.9)
argcomplete (1.7.0)
argh (0.26.1)
args (0.1.0)
argvalidate (0.9.0)
arrow (0.10.0)
attrs (16.3.0)
Babel (2.3.4)
backports.shutil-get-terminal-size (1.0.0)
bandcamp-downloader (0.0.5)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.5.1)
blessings (1.6)
burn (0.4.6)
bzr (2.8.0.dev1)
CDDB (1.4)
certifi (14.5.14)
cffi (1.7.0)
chardet (2.3.0)
clamd (1.0.1)
click (4.1)
clint (0.4.1)
cluster (1.1.1b3)
cmigemo (0.1.5)
commando (0.3.4)
configobj (5.0.6)
configparser (3.3.0.post2)
constantly (15.1.0)
contract (1.4)
cryptography (1.5.3)
cssselect (0.9.1)
darts.util.lru (0.5)
decorator (4.0.6)
demjson (2.2.2)
DisplayCAL (3.2.2.0)
dnspython (1.15.0)
docopt (0.6.2)
docutils (0.13.1)
ears (1.0.1)
eg (0.1.0)
enum34 (1.1.6)
esmre (0.3.1)
eyeD3 (0.7.10)
feedparser (5.1.3)
file-magic (0.3.0)
fontypython (0.4.6)
fpconst (0.7.2)
fudge (1.0.3)
futures (2.1.5)
galternatives (0.9)
GeoIP (1.3.2)
getmail (4.52.0)
gitdb (0.6.4)
GitPython (0.3.2rc1)
gmvault (1.9.1)
gnupg (2.0.2)
guess-language (0.2)
gyp (0.1)
hachoir-core (1.3.3)
hachoir-metadata (1.3.3)
hachoir-parser (1.3.4)
halberd (0.2.4)
howdoi (1.1.7)
html5lib (1.0b8)
http-parser (0.8.3)
httplib2 (0.9.2)
hurry.filesize (0.9)
idna (2.1)
imagesize (0.7.1)
IMAPClient (0.13)
imaplib2 (2.55)
incremental (16.10.1)
ipaddr (2.1.11)
ipaddress (1.0.17)
ipython (5.1.0)
ipython-genutils (0.1.0)
ircamhosts (0.7.1)
ircamldap (0.6.4)
isbg (0.99)
jack (3.1.1)
jedi (0.9.0)
jellyfish (0.5.6)
Jinja2 (2.8)
keyring (10.1)
kitchen (1.2.4)
launchpadlib (1.10.4)
lazr.restfulclient (0.13.4)
lazr.uri (1.0.3)
liblarch (2.1.0)
libvirt-python (2.4.0)
Logbook (0.10.1)
lxml (3.7.1)
mailnag (1.2.1)
Mako (1.0.4)
Markdown (2.6.1)
MarkupSafe (0.23)
mercurial (4.0)
msgpack-python (0.4.4)
munkres (1.0.8)
mutagen (1.36)
ndg-httpsclient (0.3.3)
netaddr (0.7.18)
NetEase-MusicBox (0.1.0.4)
netifaces (0.10.4)
nltk (3.0.1)
notmuch (0.23.3)
numpy (1.11.2)
oauth (1.0.1)
ohmu (0.5.0)
Pafy (0.3.62)
PAM (0.4.2)
paramiko (2.0.0)
Parsley (1.2)
passpie (0.2.1)
pathlib (1.0.1)
pathlib2 (2.1.0)
pdfminer (20140328)
pexpect (4.2.1)
phply (0.9.1)
pickleshare (0.7.4)
Pillow (3.4.2)
pip (8.1.2)
PLWM (2.6a0)
ply (3.9)
pocket (0.3.6)
powerline-status (dev)
prompt-toolkit (0.59)
psutil (2.2.1)
ptpython (0.27)
ptyprocess (0.5.1)
pyasn1 (0.1.3)
pyasn1-modules (0.0.7)
pybloomfiltermmap (0.3.11)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pydns (2.3.6)
pyfiglet (0.7.5)
pyflakes (1.0.0)
PyGithub (1.21.0)
Pygments (2.1.3)
pygmi (0.2)
pygobject (3.22.0)
pygpgme (0.3)
pygraphviz (1.3.1)
pyinotify (0.9.6)
pyliblzma (0.5.3)
pylogsparser (0.4)
pymad (0.9)
pymongo (3.3.1)
pyogg (1.3)
pyOpenSSL (0.13.1)
pyquery (1.2.9)
pyscard (1.9.4)
pyserial (3.2.1)
PySocks (1.6.5)
pysqlite (2.6.3)
pyte (0.4.10)
python-apt (1.1.0b5)
python-dateutil (2.4.2)
python-debian (0.1.29)
python-debianbts (2.6.1)
python-distutils-extra (2.39)
python-djvulibre (0.8)
python-hglib (2.2)
python-ldap (2.4.28)
python-magic (0.4.6)
python-musicbrainz2 (0.7.4)
python-ntlm (1.0.1)
python-slugify (1.2.0)
python-xlib (0.14)
pytz (2016.7)
pyvorbis (1.5)
pyxdg (0.25)
pyxp (0.2)
PyYAML (3.12)
rainbowstream (1.3.7)
ranger (1.7.1)
rencode (1.0.5)
reportbug (6.6.6)
requests (2.6.0)
requests-cache (0.4.10)
roman (2.0.0)
scapy-real (2.2.0.dev0)
scdl (1.1.0)
SecretStorage (2.3.1)
selenium (2.53.2)
service-identity (16.0.0)
setuptools (32.0.0)
simplegeneric (0.8.1)
simplejson (3.10.0)
simplemediawiki (1.1.1)
six (1.10.0)
slimit (0.8.1)
slugify (0.0.1)
smart (1.4)
smmap (0.9.0)
soundcloud (0.4.1)
Sphinx (1.4.8)
sphinx-rtd-theme (0.1.9)
SQLAlchemy (0.9.7)
stopit (1.1.0)
tabulate (0.7.5)
task-indicator (1.40)
tblib (0.2.0)
termcolor (1.1.0)
terminal-velocity (0.1.9)
tinydb (2.3.2)
torbrowser-launcher (0.2.6)
traitlets (4.3.1)
tritium (0.3.8)
Twisted (16.6.0)
Twisted-Lore (15.2.1)
Twisted-Web2 (8.1.0)
twitter (1.17.1)
txsocksx (0.0.0)
unicode-slugify (0.1.3)
Unidecode (0.4.19)
urllib3 (1.16)
urwid (1.1.1)
urwidtrees (1.0)
uTidylib (0.3)
uzbl (201100808)
virtualbricks (1.0.2)
virtualenv (15.1.0)
vulndb (0.0.17)
wadllib (1.3.2)
wcwidth (0.1.6)
webencodings (0.5)
wget (2.2)
wgetter (0.6)
wheel (0.29.0)
wxPython (3.0.2.0)
wxPython-common (3.0.2.0)
xdot (0.6)
xpra (0.17.6)
yagtd (0.3.4)
zope.interface (4.3.2)

Else, if I try with pip3 install, I get a :

Traceback (most recent call last):                                                        
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>                                                                                                          from bandcamp_dl.bandcamp_dl import main                                                                                                                    File "/usr/local/lib/python3.5/dist-packages/bandcamp_dl/bandcamp_dl.py", line 45, in <module>                                                                  from bandcamp import Bandcamp                                                                                                                             ImportError: No module named 'bandcamp'                                             

Thanks for your help

**Comment by Evolution0** [comment]
Strange, I tested under Python 2.7.12 and 3.5.2 without issue, this must be something specific to the way its treated as a module.

I verified this behavior myself though, sorry for the trouble.

I'll look into it ASAP

**Comment by rapha8l** [comment]
thanks !

**Comment by Evolution0** [comment]
I've fixed it, I had my imports setup for testing purposes still.

Since I don't plan on doing another full release till 0.0.6 I'll do a pre-release with the fix, here is a wheel of the fixed build: [bandcamp_downloader-0.0.6rc0-py2.py3-none-any.whl.zip](https://github.com/iheanyi/bandcamp-dl/files/674727/bandcamp_downloader-0.0.6rc0-py2.py3-none-any.whl.zip)

Just install the wheel with pip.

**Comment by rapha8l** [comment]
Thanks for your quick fix !

It works well but throw warnings :
    
WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/dist-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module                                                                                                                                                      WARNING: yacc table file version is out of date                                                                                                               WARNING: Token 'IMPORT' defined, but not used                                                                                                                 WARNING: Token 'BLOCK_COMMENT' defined, but not used                                                                                                          WARNING: Token 'ENUM' defined, but not used                                                                                                                   WARNING: Token 'EXTENDS' defined, but not used                                                                                                                WARNING: Token 'LINE_COMMENT' defined, but not used                                                                                                           WARNING: Token 'LINE_TERMINATOR' defined, but not used                                                                                                        WARNING: Token 'CONST' defined, but not used                                                                                                                  WARNING: Token 'EXPORT' defined, but not used                                                                                                                 WARNING: Token 'CLASS' defined, but not used                                                                                                                  WARNING: Token 'SUPER' defined, but not used                                                                                                                  WARNING: There are 10 unused tokens                                                                                                                           WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/local/lib/python2.7/dist-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule       WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/dist-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module                                                                                                                                                      WARNING: yacc table file version is out of date  
WARNING: Token 'IMPORT' defined, but not used                                                                                                        [48/6638]WARNING: Token 'BLOCK_COMMENT' defined, but not used                                                                                                          WARNING: Token 'ENUM' defined, but not used                                                                                                                   WARNING: Token 'EXTENDS' defined, but not used                                                                                                                WARNING: Token 'LINE_COMMENT' defined, but not used                                                                                                           WARNING: Token 'LINE_TERMINATOR' defined, but not used                                                                                                        WARNING: Token 'CONST' defined, but not used                                                                                                                  WARNING: Token 'EXPORT' defined, but not used                                                                                                                 WARNING: Token 'CLASS' defined, but not used                                                                                                                  WARNING: Token 'SUPER' defined, but not used                                                                                                                  WARNING: There are 10 unused tokens                                                                                                                           WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/local/lib/python2.7/dist-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule       WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/dist-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module                                                                                                                                                      WARNING: yacc table file version is out of date                                                                                                               WARNING: Token 'IMPORT' defined, but not used                                                                                                                 WARNING: Token 'BLOCK_COMMENT' defined, but not used                                                                                                          WARNING: Token 'ENUM' defined, but not used                                                                                                                   WARNING: Token 'EXTENDS' defined, but not used                                                                                                                WARNING: Token 'LINE_COMMENT' defined, but not used                                                                                                           WARNING: Token 'LINE_TERMINATOR' defined, but not used                                                                                                        WARNING: Token 'CONST' defined, but not used                                                                                                                  WARNING: Token 'EXPORT' defined, but not used                                                                                                                 WARNING: Token 'CLASS' defined, but not used                                                                                                                  WARNING: Token 'SUPER' defined, but not used                                                                                                                  WARNING: There are 10 unused tokens                                                                                                                          
WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/local/lib/python2.7/dist-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule
Starting download process.

**Comment by Evolution0** [comment]
Those are harmless and due to slimit (out of our control).

You can make them go away though, delete lextab and yacctab from the slimit directory in site-packages. For some reason it comes with its own and freaks out as it attempts to overwrite them but can't. (They autogenerate anyway)

**Comment by rapha8l** [comment]
Great, thanks again

**Comment by Evolution0** [comment]
No problem, if you run into any other issues be sure to let us know 😸
