### ISSUE TITLE
Embed Lyrics Redux

### ISSUE THREAD

**Issue by Evolution0** [Evolution0/bandcamp-dl#77]
For some reason even with all lyric grabbing and embedding code disabled lyrics are still embedded somehow.

It must  somehow be embedded to begin with but I was under the impression the mp3's where metadata bare to start with?

If they are embedded to begin with what was the point of the original PR?

I was getting strange cases of duplicated lyrics tags (Lyrics and Lyrics [None] in Picard) and so I'm guessing the tag was there to begin with.

Its possible that some artists release theirs with the lyrics properly embedded and some don't and that was the reasoning but as it stands not checking if the lyrics are embedded already before doing so is a big no no.

**Comment by iheanyi** [comment]
🤔 Maybe they come embedded based on the MP3s? Hm. Good catch.

**Comment by Evolution0** [comment]
It seems that way, I tried with and without the lyrics code and all it did was add a duplicate lyrics tag labeled `lyrics[none]` that contained the same data. I ended up reverting to the original code.

Anyway just pushed out some fixes in 0.0.6 and added --no-art, the fixes are important so I'll be pushing 0.0.6 as a new release on PyPI in a bit.

**Comment by Evolution0** [comment]
Re-opening this, after thinking about it I believe the issue is due to the fact that we don't sanitize our MP3s before encoding so we could end up duplicating tags in some cases.

We need to check if lyrics are not already embedded but are available in the JSON, if they are available and not already embedded then do so if the --embed-lyrics option is used.

..Note to self: Add a sanitizing step somewhere in the encoding process.

**Comment by Evolution0** [comment]
I should be able to add this in now that tracks are sanitized.

Edit: Alright so now that we have proper JSON from TralbumData we can use the has_lyrics item to see if it has lyrics or not, though some lyrics are embedded in the album data some are not (has_lyrics = True but lyrics item is empty) they seem to be included in the page in a hide-able div, luckily the divs are numbered by track order so scraping it per track should be fairly straight forward.

Edit: Seems they are loaded dynamically so without leveraging Selenium and PhantomJS adding lyrics not contained in the JSON seems to be unrealistic. I don't feel its a good idea to require another dependency and a separate download just for lyrics. I will however leave the functionality in to embed lyrics contained in the JSON.

Edit 2: Done, in the case that lyrics are not available in the JSON and the option is used placeholder text will be inserted. ("lyrics unavailable")

**Comment by Evolution0** [comment]
I came across some interesting things now that I have finally gotten around to writing tests, when grabbing JSON with the album url as the source the lyrics are dynamically shown on the page and not included in the JSON but interestingly enough when using a track link (even from a track in the same album) the lyrics are properly included in the JSON.

And it seems the page source that BeautifulSoup ends up parsing is a bit different to what you see in the browser due to some JS trickery, the lyrics are not in divs when grabbing the page directly, they are in `<dd>` tags!

There may be hope yet for getting the lyrics properly.

**Comment by iheanyi** [comment]
Nice!

**Comment by Evolution0** [comment]
Done
