### ISSUE TITLE
chinese characters

### ISSUE THREAD

**Issue by arnauldb** [Evolution0/bandcamp-dl#78]
Thanks for bandcamp-dl. However it seems I can't download when there are chinese characters, like this page https://guiguisuisui.bandcamp.com/album/wu-xing

**Comment by Evolution0** [comment]
I literally just uploaded version 0.0.6 to both PyPI and the repo, upgrade and see if it still happens. 😸

Edit: I just tested under Python 3.5.2 and 2.7.12, it works correctly under 3.5.2 but not 2.7.12 though I know why and can fix it quickly. Give me a bit.

Also are you installing via pip or from source?

Edit 2: Alright updated with the fix, I retested and that album now downloads fine under both versions. I should have it up on PyPI in a moment.

Edit 3: Bugfix release up on PyPI, you should be able to simply upgrade now. Thanks for pointing this out.

**Comment by arnauldb** [comment]
that's very nice. Thank you.

And how to upgrade ? I installed from source.

**Comment by Evolution0** [comment]
Just `pip install --upgrade bandcamp-downloader`

**Comment by arnauldb** [comment]
maybe I am mistaking, but I think there are a few typos...

-when I installed version 0.0.5 from source, I had to change "bandcamp_dl.py" to "bandcamp-dl.py" then "python bandcamp-dl.py https://...t" from the "bandcamp_dl" directory. It worked fine except for the chinese characters problem. 

I then downloaded the latest version 0.0.6 to install from source but can't get it working at all even if I change the "_" for "-" ...

If I install from pip I can't get it working if I run "python bandcamp-dl.py https://..."

So I am stucked with version 0.0.5 installed from source...which is working for me except for the chinese character problem.

**Comment by Evolution0** [comment]
Open CMD and run: `pip install bandcamp-downloader`. You will then be able to use it as documented: `bandcamp-dl URL etc etc`

The naming is correct, when its "built" it creates a bandcamp-dl.exe

Running from source in 0.0.5 only works because the imports were not updated, its meant to be installed via pip now.

~~The from source instructions need to be changed/removed.~~
Source install instructions updated.

**Comment by arnauldb** [comment]
it doesn't work for me. I installed from pip, it says it is installed, then I "bandcamp-dl.py https://..."

and I have

"bandcamp-dl.py https://...
bandcamp-dl.py: command not found
"

...I guess I am missing something. I am using Ubuntu.

**Comment by Evolution0** [comment]
Try typing just `bandcamp-dl` without the `.py`.

**Comment by Evolution0** [comment]
I'm assuming this was solved.
