### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Evolution0** [Evolution0/bandcamp-dl#84]
We have been needing this, its a bit silly that testing has been done manually.

I'll get together a nice group of urls with different album sizes, languages, etc and put together some tests with pytest.

Not sure if tests for individual tracks should be put in yet as currently it only works by coincidence, there is no actual code for handling individual tracks and they are downloaded as if they were albums.

**Comment by iheanyi** [comment]
In terms of testing this, it'll probably be best to figure out how to best mock out this Bandcamp Service and just use an example file locally as the static file to download. But yeah, I agree that a good test suite for this would be beneficial.

**Comment by Evolution0** [comment]
Indeed, spamming the site with requests while testing wouldn't be good and it would be much slower.

We would need:
- Test album pages with the same structure as BC
- A dummy script element containing information for each album
- Sets of small MP3 files for each album with multilingual filenames

Album information contained in the dummy script should also contain strings in different languages.

The MP3 files can simply be a second of silence as its only for testing purposes.

Hosting the dummy server is easy, the built in `http.server` module is enough but if developing in PyCharm it automatically puts one up when previewing a page though doing so with `http.server` would be best that way the server can be initialized with the test script.

**Comment by iheanyi** [comment]
If this was written in Go, I'd have the perfect idea of how to do this testing stuff. I'll noodle on it some more and find some resources to help you out.

**Comment by Evolution0** [comment]
Pushed back, and needs its own project.

**Comment by Evolution0** [comment]
Might be a good idea to use [Enforce](https://github.com/RussBaz/enforce) to enforce the new typehints I've added and provide detailed tracebacks related to them during testing.

**Comment by iheanyi** [comment]
👀

**Comment by Evolution0** [comment]
For now I believe I will create some mockup pages to at least get some of the tests working (JSON retrieval, page scraping, etc)

Edit: Mockup pages for Track, Album, Artist, and Discography are done, all tests pass for the basic JSON generation and value assignment.

Discography page isn't really used yet, bandcamp-dl just isn't equipped to parse it currently (though I hope to add it)

**Comment by Evolution0** [comment]
I kinda know how to do this finally, I was going in the wrong direction.

There already exists libraries for caching requests locally for consistent testing and now that I know how they work (and sorta know how to write unittests) I should be able to at least mock up the requesting and parsing bits. As for testing the mp3s I can just make some blank files with the same names as the mockup pages tracks and test the encoding on them.
