### ISSUE TITLE
Support for non-ascii characters

### ISSUE THREAD

**Issue by geezuh** [Evolution0/bandcamp-dl#88]
When downloading an album with non-english characters, I get the following error:

'ascii' codec can't encode characters in position 60-62: ordinal not in range(128)

**Comment by Evolution0** [comment]
What version of Python?
What version of bandcamp-dl?

And please provide the album/track url you used.

**Comment by geezuh** [comment]
python --version
Python 2.7.9

bandcamp-dl --version
bandcamp-dl 0.0.6-01

bandcamp-dl https://ailanthusrecordings.bandcamp.com/track/h3art-feat-magician              
Starting download process.
Accessing track 1 of 1
'ascii' codec can't encode characters in position 50-52: ordinal not in range(128)
Downloading failed..

**Comment by Evolution0** [comment]
Hm, I had assumed any version in the 2.7 series was safe, I can confirm that it works correctly with that url under 2.7.12 and 3.5.2. 

Are you unable to update python at this time?

**Comment by geezuh** [comment]
I'm using the one from the debian apt. I'd rather not build python myself.
I'll play around and see if i can get this to build in 3, I had an issue originally so I fell back on 2.7

**Comment by Evolution0** [comment]
Simply do: `pip install bandcamp-downloader` recent versions are universal wheels that should install just fine regardless of OS or architecture.

As for python you can install packages from the testing repo (Which have Python 2.7.13 now)
Take a look at this: http://serverfault.com/questions/22414/how-can-i-run-debian-stable-but-install-some-packages-from-testing

Though I have an idea what could be causing this issue (string encoding) the next release of bandcamp-dl won't support Python 2 at all and setting up a dev environment for an outdated version to fix it is counter-productive. 😞
