### ISSUE TITLE
AttributeError: 'Bandcamp' object has no attribute 'tralbum_data_json'

### ISSUE THREAD

**Issue by maximtrp** [Evolution0/bandcamp-dl#96]
**Python version:**  
Python 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609] on linux

**Bandcamp-dl version:**
bandcamp-dl 0.0.7-02 (installed from PyPi)

**Bancamp-dl options:**  

**URL:**  
https://bvdub.bandcamp.com/album/safety-in-a-number

**Options:**  

**Describe the issue:**
-------------------------
When I try to download an album or a track, I get:

```
String literal is not terminated
Traceback (most recent call last):
  File "/home/maksim/.local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/home/maksim/.local/lib/python3.5/site-packages/bandcamp_dl/bandcamp_dl.py", line 77, in main
    album = bandcamp.parse(url)
  File "/home/maksim/.local/lib/python3.5/site-packages/bandcamp_dl/bandcamp.py", line 27, in parse
    self.tracks = self.tralbum_data_json['trackinfo']
AttributeError: 'Bandcamp' object has no attribute 'tralbum_data_json'
```

**Comment by Evolution0** [comment]
Well that is interesting, the link isn't special, the contents should be the same as every album.. TralbumData is present on the page as it should be and in the usual format.

I can verify that this is indeed a bug and not Linux specific so that is good.

Looking into it.

**Comment by Evolution0** [comment]
Seems this album has a much longer more detailed TralbumData dict that at some point has a ";" (Edit: It does as suspected) somewhere in it. Its never being terminated correctly so can't be converted to JSON properly.

Looks like I need to make the JSON generator more robust.

**Comment by Evolution0** [comment]
I need to refine the regex to ignore ";"s that are not adjacent to "}", my temporary solution will work for now. Adding regex refinement to my todo.

Edit: New release tagged and new release on PyPI, `pip install --upgrade bandcamp-downloader` for the fix.

**Comment by skeletonsaurus** [comment]
I have the most up to date version, and I am still encountering the issue (the exact same error output as above). I have tried multiple urls. For example: https://telefuturenow.bandcamp.com/album/left-to-our-own-devices

**Comment by Evolution0** [comment]
@skeletonsaurus I'm guessing it is a similar error (My JSON generator has lackluster error messages atm) I just tried your link with my latest code (The proper regex update) and it works fine, looks like I need to push out the proper bugfix release. Thanks for letting me know.

Edit: 0.0.7-04 released here and on PyPI, go ahead and upgrade.
