### ISSUE TITLE
invalid syntax issue

### ISSUE THREAD

**Issue by skeletonsaurus** [Evolution0/bandcamp-dl#98]
**Python version:**  
2.7.13
**Bandcamp-dl version:**
0.0.7
**Bancamp-dl options:**  

**url:**  

**options:**  

**Describe the issue:**
-------------------------
     Traceback (most recent call last):
 
     File "bandcamp-dl/bandcamp_dl/bandcamp_dl.py", line 49, in <module>
   
       from bandcamp import Bandcamp
  
    File "/home/ergo/Music/bandcamp-dl/bandcamp_dl/bandcamp.py", line 9

       def parse(self, url: str, art: bool=True) -> dict or None:
                          ^
    SyntaxError: invalid syntax

**Comment by Evolution0** [comment]
Last version to support Python 2.7.x is 0.0.6-02.

When it doubt check the release notes for specific [releases](https://github.com/iheanyi/bandcamp-dl/releases).

**Comment by skeletonsaurus** [comment]
Thanks!
