### ISSUE TITLE
KeyError: 'album_title'

### ISSUE THREAD

**Issue by skeletonsaurus** [Evolution0/bandcamp-dl#99]
**Python version:**  
3.5.3rc1
**Bandcamp-dl version:**
0.0.7-04
**Bancamp-dl options:**  
default
**url:**  
any
**options:**  

**Describe the issue:**
-------------------------
Was working fine, then suddenly it started throwing the following error, for any url I tested. 

Traceback (most recent call last):
  File "/home/ergo/py3env/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/home/ergo/py3env/lib/python3.5/site-packages/bandcamp_dl/bandcamp_dl.py", line 77, in main
    album = bandcamp.parse(url)
  File "/home/ergo/py3env/lib/python3.5/site-packages/bandcamp_dl/bandcamp.py", line 31, in parse
    "title": self.embed_data_json['album_title'],
KeyError: 'album_title'

**Comment by Evolution0** [comment]
Strange, I've tested it under 3.5.2, 3.5.3, and 3.6.0 without issue. May be an issue with the release candidate you are using?

Post some of the urls, might be something obscure.

**Comment by dindon-sournois** [comment]
Same situation as @skeletonsaurus with python 3.6.0 (bandcamp-dl installed with pip)

Here is some url that aren't working :
> EDITED

**Comment by Evolution0** [comment]
Try upgrading to the latest version: `pip install --upgrade bandcamp-downloader`

I've made some changes that may possibly fix this.

**Comment by dindon-sournois** [comment]
The issue remains, at least for the url I listed.

**Comment by Evolution0** [comment]
Indeed, it silently fails to retrieve the page at all. Lets see if I can fix that..

**Comment by Evolution0** [comment]
I know the problem here. The other links were throwing me off (because they work), its track url specific.  

There is obviously no album title if its a single. So I just need to check for that and add in some alternative values.

**Comment by Evolution0** [comment]
New build up, try upgrading again.

**Comment by dindon-sournois** [comment]
Yep, you fixed it! Thanks to you.

**Comment by Evolution0** [comment]
No problem. 

Now I just need confirmation from @skeletonsaurus that its fixed any issues with the urls they used.

**Comment by skeletonsaurus** [comment]
Yes it fixed it. Thanks!
